<template>
  <div class="mx-auto max-w-5xl space-y-6">
    <div><p class="text-sm font-semibold text-primary">ORGANIZATION</p><h2 class="mt-1 text-2xl font-semibold">Affiliations & memberships</h2><p class="mt-2 text-sm text-slate-500">Record memberships only for an area you are responsible for.</p></div>
    <UCard v-if="isOwner"><template #header><h3 class="font-semibold">Governing body directory</h3></template><form class="grid gap-4 sm:grid-cols-3" @submit.prevent="addBody"><UInput v-model="body.name" placeholder="Governing body name" required /><USelect v-model="body.level" :items="levels" /><UButton type="submit" :loading="savingBody">Add governing body</UButton></form></UCard>
    <UCard><template #header><div><h3 class="font-semibold">Record membership</h3><p class="mt-1 text-sm text-slate-500">Choose the governing body and the hierarchy node or dojo it applies to.</p></div></template><div v-if="!bodyOptions.length" class="rounded-xl bg-amber-50 p-4 text-sm text-amber-800 dark:bg-amber-950/30 dark:text-amber-200">No governing bodies have been added yet. Ask the organization owner to add one first.</div><form v-else class="grid gap-4 sm:grid-cols-3" @submit.prevent="addAffiliation"><USelect v-model="affiliation.governingBodyId" :items="bodyOptions" placeholder="Governing body" /><USelect v-model="affiliation.relationshipType" :items="relationshipTypes" /><USelect v-model="affiliation.scopeType" :items="scopeTypes" @update:model-value="affiliation.scopeId = null" /><USelect v-if="affiliation.scopeType !== 'organization'" v-model="affiliation.scopeId" :items="scopeOptions" placeholder="Select assigned scope" /><UInput v-model="affiliation.renewalDueAt" type="date" /><UButton type="submit" :loading="savingAffiliation">Record affiliation</UButton></form></UCard>
    <UCard><template #header><h3 class="font-semibold">Current relationships</h3></template><div v-if="affiliations?.length" class="divide-y divide-slate-100 dark:divide-slate-800"><div v-for="item in affiliations" :key="item.id" class="flex justify-between py-4"><div><p class="font-medium">{{ item.governingBody.name }}</p><p class="mt-1 text-sm capitalize text-slate-500">{{ item.relationshipType.replaceAll('_', ' ') }} · {{ item.scopeType }}</p></div><UBadge class="capitalize" color="primary">{{ item.status }}</UBadge></div></div><p v-else class="py-8 text-center text-sm text-slate-500">No affiliations recorded.</p></UCard>
  </div>
</template>
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const { user } = useUserSession(); const isOwner = computed(() => user.value?.role === 'owner'); const toast = useToast(); const savingBody = ref(false); const savingAffiliation = ref(false)
const body = reactive({ name: '', level: 'other' }); const affiliation = reactive({ governingBodyId: undefined as number | undefined, relationshipType: 'membership', scopeType: 'organization', scopeId: null as number | null, renewalDueAt: '' })
const levels = ['international', 'national', 'state', 'district', 'city', 'local', 'other'].map(value => ({ label: value, value })); const relationshipTypes = ['parent_affiliation', 'membership', 'recognition', 'license', 'accreditation'].map(value => ({ label: value.replaceAll('_', ' '), value }))
const { data: bodies, refresh: refreshBodies } = await useFetch<any[]>('/api/governing-bodies'); const { data: affiliations, refresh: refreshAffiliations } = await useFetch<any[]>('/api/affiliations'); const { data: permissions } = await useFetch<any>('/api/users/me/permissions'); const { data: nodes } = await useFetch<any[]>('/api/hierarchy/nodes'); const { data: dojos } = await useFetch<any[]>('/api/dojos')
const bodyOptions = computed(() => (bodies.value || []).map(item => ({ label: item.name, value: item.id }))); const scopeTypes = computed(() => isOwner.value ? [{ label: 'Organization-wide', value: 'organization' }, { label: 'Hierarchy node', value: 'node' }, { label: 'Dojo', value: 'dojo' }] : [{ label: 'Hierarchy node', value: 'node' }, { label: 'Dojo', value: 'dojo' }]); const flatNodes = computed(() => flattenNodes(nodes.value || [])); const scopeOptions = computed(() => affiliation.scopeType === 'dojo' ? (dojos.value || []).filter(dojo => permissions.value?.allowedDojoIds?.includes(dojo.id)).map(dojo => ({ label: dojo.name, value: dojo.id })) : flatNodes.value.filter(node => permissions.value?.allowedNodeIds?.includes(node.id)).map(node => ({ label: node.name, value: node.id })))
watch(isOwner, value => { if (!value && affiliation.scopeType === 'organization') affiliation.scopeType = 'node' }, { immediate: true }); function flattenNodes(tree: any[]): any[] { return tree.flatMap(node => [node, ...flattenNodes(node.children || [])]) }
async function addBody() { savingBody.value = true; try { await $fetch('/api/governing-bodies', { method: 'POST', body }); body.name = ''; await refreshBodies(); toast.add({ color: 'success', title: 'Governing body added' }) } catch (error: any) { toast.add({ color: 'error', title: 'Could not add governing body', description: error.data?.statusMessage || error.message }) } finally { savingBody.value = false } }
async function addAffiliation() { if (!affiliation.governingBodyId || (affiliation.scopeType !== 'organization' && !affiliation.scopeId)) { toast.add({ color: 'warning', title: 'Select a governing body and assigned scope' }); return } savingAffiliation.value = true; try { await $fetch('/api/affiliations', { method: 'POST', body: { ...affiliation, status: 'active', renewalDueAt: affiliation.renewalDueAt || undefined } }); await refreshAffiliations(); toast.add({ color: 'success', title: 'Affiliation recorded' }) } catch (error: any) { toast.add({ color: 'error', title: 'Could not record affiliation', description: error.data?.statusMessage || error.message }) } finally { savingAffiliation.value = false } }
</script>
