<template>
  <div class="mx-auto max-w-4xl"><section class="mb-6"><p class="text-sm font-semibold text-primary">ORGANIZATION</p><h2 class="mt-1 text-2xl font-semibold">Martial arts & programs</h2><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Manage the disciplines and styles your organization teaches.</p></section><UCard><form class="grid gap-4 sm:grid-cols-3" @submit.prevent="addProgram"><UFormField label="Martial art" required><UInput v-model="form.martialArt" placeholder="e.g. Karate" /></UFormField><UFormField label="Style / lineage" required><UInput v-model="form.style" placeholder="e.g. Goju-ryu" /></UFormField><div class="flex items-end"><UButton type="submit" :loading="saving" icon="i-lucide-plus">Add program</UButton></div></form></UCard><UCard class="mt-6"><template #header><h3 class="font-semibold">Active programs</h3></template><div v-if="programs?.length" class="divide-y divide-slate-100 dark:divide-slate-800"><div v-for="program in programs" :key="program.id" class="flex items-center justify-between py-4"><div><p class="font-medium">{{ program.displayName }}</p><p class="mt-1 text-sm text-slate-500">{{ program.martialArt }} · {{ program.style }}</p></div><UBadge v-if="program.isPrimary" color="primary">Primary</UBadge></div></div><p v-else class="py-8 text-center text-sm text-slate-500">No programs configured.</p></UCard></div>
</template>
<script setup lang="ts">
definePageMeta({ middleware: ['auth', 'admin'] })
type Program = { id: number, martialArt: string, style: string, displayName: string, isPrimary: number }
const toast = useToast(); const saving = ref(false); const form = reactive({ martialArt: '', style: '' }); const { data: programs, refresh } = await useFetch<Program[]>('/api/organization/programs')
async function addProgram() { saving.value = true; try { await $fetch('/api/organization/programs', { method: 'POST', body: form }); Object.assign(form, { martialArt: '', style: '' }); await refresh(); toast.add({ color: 'success', title: 'Program added' }) } catch (error: any) { toast.add({ color: 'error', title: 'Could not add program', description: error.data?.statusMessage || error.message }) } finally { saving.value = false } }
</script>
