<template>
  <div class="mx-auto max-w-5xl">
    <section v-if="data" class="mb-6"><p class="text-sm font-semibold text-primary">STUDENT PORTAL</p><h1 class="mt-1 text-2xl font-semibold">Welcome, {{ data.student.firstName }}</h1><p class="mt-2 text-sm text-slate-500">{{ data.student.dojo?.name || 'Your dojo' }} · View your records and keep your contact details current.</p></section>
    <div v-if="pending" class="space-y-4"><USkeleton class="h-24" /><USkeleton class="h-64" /></div>
    <UAlert v-else-if="error" color="error" title="Could not load your portal" description="Please try again." />
    <template v-else-if="data">
      <div class="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><UCard><p class="text-sm text-slate-500">Current rank</p><p class="mt-2 text-xl font-semibold">{{ data.student.currentBeltRank?.name || 'Not assigned' }}</p><p class="mt-1 text-sm text-slate-400">{{ data.student.currentBeltRank?.level || '' }}</p></UCard><UCard><p class="text-sm text-slate-500">Attendance</p><p class="mt-2 text-xl font-semibold">{{ data.attendanceSummary.rate }}%</p><p class="mt-1 text-sm text-slate-400">{{ data.attendanceSummary.present }} of {{ data.attendanceSummary.total }} attended</p></UCard><UCard><p class="text-sm text-slate-500">Achievements</p><p class="mt-2 text-xl font-semibold">{{ data.achievements.length }}</p></UCard><UCard><p class="text-sm text-slate-500">Payments recorded</p><p class="mt-2 text-xl font-semibold">{{ data.payments.length }}</p></UCard></div>
      <div class="mb-5 flex flex-wrap gap-2"><UButton v-for="item in tabs" :key="item.value" size="sm" :color="tab === item.value ? 'primary' : 'neutral'" :variant="tab === item.value ? 'solid' : 'soft'" @click="tab = item.value">{{ item.label }}</UButton></div>
      <UCard v-if="tab === 'profile'"><template #header><h2 class="font-semibold">My profile</h2></template><form class="grid gap-4 sm:grid-cols-2" @submit.prevent="saveProfile"><UFormField label="Email"><UInput v-model="profile.email" type="email" /></UFormField><UFormField label="Phone"><UInput v-model="profile.phone" /></UFormField><UFormField label="Address" class="sm:col-span-2"><UInput v-model="profile.address" /></UFormField><UFormField label="Emergency contact"><UInput v-model="profile.emergencyContact" /></UFormField><UFormField label="Emergency phone"><UInput v-model="profile.emergencyPhone" /></UFormField><div class="sm:col-span-2"><UButton type="submit" :loading="savingProfile">Save contact details</UButton></div></form></UCard>
      <UCard v-else-if="tab === 'progress'"><template #header><div class="flex items-center justify-between"><h2 class="font-semibold">My progress</h2><UButton :href="`/api/students/${data.student.id}/progress-report`" target="_blank" size="sm" icon="i-lucide-download">Progress report</UButton></div></template><div v-if="data.gradings.length" class="space-y-3"><div v-for="grading in data.gradings" :key="grading.id" class="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><p class="font-medium">{{ grading.beltRank?.name }} <span class="text-slate-500">{{ grading.beltRank?.level }}</span></p><p class="mt-1 text-sm text-slate-500">Awarded {{ formatDate(grading.awardedDate) }}</p><p v-if="grading.certificateNumber" class="mt-1 text-sm">Certificate: {{ grading.certificateNumber }}</p><a v-if="grading.certificateUrl" :href="grading.certificateUrl" target="_blank" class="mt-2 inline-block text-sm text-primary hover:underline">Open certificate</a></div></div><p v-else class="py-8 text-center text-slate-500">No gradings have been recorded yet.</p></UCard>
      <UCard v-else-if="tab === 'achievements'"><template #header><h2 class="font-semibold">My achievements</h2></template><div v-if="data.achievements.length" class="space-y-3"><div v-for="item in data.achievements" :key="item.id" class="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><p class="font-medium">{{ item.tournamentName }}</p><p class="mt-1 text-sm text-slate-500">{{ item.eventType || 'Participation' }} · {{ formatDate(item.startDate) }}</p><p class="mt-1 text-sm">{{ item.result || 'Participation' }}<span v-if="item.medalType"> · {{ item.medalType }}</span></p><a v-if="item.certificateUrl" :href="item.certificateUrl" target="_blank" class="mt-2 inline-block text-sm text-primary hover:underline">Open certificate</a></div></div><p v-else class="py-8 text-center text-slate-500">No achievements have been recorded yet.</p></UCard>
      <UCard v-else-if="tab === 'fees'"><template #header><h2 class="font-semibold">My fee payments</h2></template><div v-if="data.payments.length" class="divide-y divide-slate-100 dark:divide-slate-800"><div v-for="payment in data.payments" :key="payment.id" class="flex items-center justify-between gap-4 py-4"><div><p class="font-medium">{{ formatCurrency(payment.amount) }}</p><p class="mt-1 text-sm text-slate-500">{{ formatDate(payment.paymentDate) }} · {{ payment.method }}</p></div><p class="text-sm text-slate-500">{{ payment.receiptNumber }}</p></div></div><p v-else class="py-8 text-center text-slate-500">No payments have been recorded yet.</p></UCard>
      <UCard v-else-if="tab === 'attendance'"><template #header><div class="flex items-center justify-between"><h2 class="font-semibold">My attendance</h2><UBadge color="primary" variant="subtle">{{ data.attendanceSummary.rate }}% attendance</UBadge></div></template><div class="mb-4 rounded-lg bg-primary/5 p-3 text-sm text-slate-600 dark:text-slate-300">Your attendance is <strong>{{ data.attendanceSummary.rate }}%</strong>. You need at least <strong>80% attendance</strong> to qualify for the next grading; final eligibility remains subject to instructor assessment and dojo policy.</div><div v-if="data.attendance.length" class="divide-y divide-slate-100 dark:divide-slate-800"><div v-for="record in data.attendance" :key="record.id" class="flex flex-wrap items-center justify-between gap-3 py-4"><div><p class="font-medium">{{ record.session?.name || 'Class' }}</p><p class="mt-1 text-sm text-slate-500">{{ formatDate(record.session?.date) }} · {{ record.session?.startTime }}–{{ record.session?.endTime }} · {{ record.session?.dojo?.name || data.student.dojo?.name }}</p><p v-if="record.notes" class="mt-1 text-sm text-slate-500">{{ record.notes }}</p></div><UBadge :color="attendanceColor(record.status)" variant="subtle" class="capitalize">{{ record.status }}</UBadge></div></div><p v-else class="py-8 text-center text-slate-500">No attendance has been recorded yet.</p></UCard>
      <UCard v-else><template #header><h2 class="font-semibold">My documents</h2></template><div v-if="data.documents.length" class="divide-y divide-slate-100 dark:divide-slate-800"><a v-for="document in data.documents" :key="document.id" :href="document.fileUrl" target="_blank" class="flex items-center justify-between py-4 text-primary hover:underline"><span>{{ document.documentType.replaceAll('_', ' ') }}</span><UIcon name="i-lucide-external-link" /></a></div><p v-else class="py-8 text-center text-slate-500">No documents have been shared yet.</p></UCard>
    </template>
  </div>
</template>
<script setup lang="ts">
definePageMeta({ middleware: 'auth', layout: 'portal' })
const { user } = useUserSession(); if (user.value?.role !== 'student') await navigateTo('/')
const toast = useToast(); const tab = ref('profile'); const savingProfile = ref(false); const tabs = [{ label: 'Profile', value: 'profile' }, { label: 'Attendance', value: 'attendance' }, { label: 'Progress', value: 'progress' }, { label: 'Achievements', value: 'achievements' }, { label: 'Fees', value: 'fees' }, { label: 'Documents', value: 'documents' }]
const { data, pending, error, refresh } = await useFetch<any>('/api/portal/me')
const { data: organization } = await useFetch<{ currency?: string }>('/api/organization/settings')
const profile = reactive({ email: '', phone: '', address: '', emergencyContact: '', emergencyPhone: '' })
watchEffect(() => { if (data.value) Object.assign(profile, { email: data.value.student.email || '', phone: data.value.student.phone || '', address: data.value.student.address || '', emergencyContact: data.value.student.emergencyContact || '', emergencyPhone: data.value.student.emergencyPhone || '' }) })
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) }; function formatCurrency(amount: number) { return new Intl.NumberFormat(undefined, { style: 'currency', currency: organization.value?.currency || 'USD' }).format(amount / 100) }
function attendanceColor(status: string) { return status === 'present' ? 'success' : status === 'late' ? 'warning' : status === 'excused' ? 'info' : 'error' }
async function saveProfile() { savingProfile.value = true; try { await $fetch('/api/portal/profile', { method: 'PATCH', body: profile }); await refresh(); toast.add({ color: 'success', title: 'Profile updated' }) } catch (error: any) { toast.add({ color: 'error', title: 'Could not update profile', description: error.data?.statusMessage || error.message }) } finally { savingProfile.value = false } }
</script>
