<template>
  <div class="mx-auto max-w-6xl">
    <section class="mb-6"><p class="text-sm font-semibold text-primary">OPERATIONS</p><h1 class="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Attendance</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Choose a dojo to see every class session and its attendance records.</p></section>
    <UCard class="mb-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center"><div class="min-w-0 flex-1"><p class="font-semibold">Which dojo are you working with?</p><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Only dojos you are allowed to manage are shown.</p></div><USelect v-model="selectedDojoId" :items="dojoOptions" placeholder="Select a dojo" class="w-full sm:w-72" @update:model-value="onDojoChange" /></div></UCard>
    <UAlert v-if="!selectedDojoId" color="neutral" variant="subtle" icon="i-lucide-calendar-check-2" title="Select a dojo to view attendance" description="Its class sessions and individual student records will appear here." />
    <template v-else>
      <section class="mb-6 grid gap-3 sm:grid-cols-3"><div v-for="item in summary" :key="item.label" class="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p class="text-sm text-slate-500 dark:text-slate-400">{{ item.label }}</p><p class="mt-2 text-xl font-semibold">{{ item.value }}</p></div></section>
      <UCard class="mb-6"><template #header><div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold">Add a class session</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Use this when you are ready to take attendance for a new class.</p></div><UButton size="sm" color="primary" :icon="showSessionForm ? 'i-lucide-x' : 'i-lucide-plus'" @click="showSessionForm = !showSessionForm">{{ showSessionForm ? 'Close' : 'Add session' }}</UButton></div></template><form v-if="showSessionForm" class="grid gap-4 md:grid-cols-3" @submit.prevent="createSession"><UFormField label="Class date" required><UInput v-model="newSessionDate" type="date" required /></UFormField><UFormField label="Use a saved class time"><USelect v-model="selectedScheduleId" :items="scheduleOptions" placeholder="Optional" @update:model-value="autoFillFromSchedule" /></UFormField><UFormField label="Instructor"><USelect v-model="newSessionInstructorId" :items="instructorOptions" placeholder="Optional" /></UFormField><UFormField label="Starts at" required><UInput v-model="newSessionStart" type="time" required /></UFormField><UFormField label="Ends at" required><UInput v-model="newSessionEnd" type="time" required /></UFormField><UFormField label="Class name"><UInput v-model="newSessionName" placeholder="Optional" /></UFormField><div class="md:col-span-3 flex justify-end"><UButton type="submit" :loading="creatingSession">Save session</UButton></div></form></UCard>
      <UCard><template #header><div><h2 class="font-semibold">Attendance records for {{ selectedDojo?.name }}</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Open a class session to view or update every student’s attendance.</p></div></template><p v-if="loadingSessions" class="text-sm text-slate-500">Loading class sessions...</p><div v-else-if="!sessions.length" class="py-10 text-center"><UIcon name="i-lucide-calendar-x" class="mx-auto h-7 w-7 text-slate-300" /><p class="mt-3 text-sm text-slate-500">No class sessions have been added for this dojo yet.</p></div><div v-else class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="border-b border-slate-100 text-left text-xs uppercase tracking-wide text-slate-400 dark:border-slate-800"><tr><th class="px-3 py-3">Date</th><th class="px-3 py-3">Class</th><th class="px-3 py-3">Time</th><th class="px-3 py-3">Instructor</th><th class="px-3 py-3">Attendance</th><th class="px-3 py-3 text-right">Actions</th></tr></thead><tbody><tr v-for="sess in sessions" :key="sess.id" class="border-b border-slate-100 last:border-0 dark:border-slate-800"><td class="px-3 py-4 font-medium">{{ formatDate(sess.date) }}</td><td class="px-3 py-4">{{ sess.name || 'Class' }}</td><td class="px-3 py-4 text-slate-600 dark:text-slate-300">{{ sess.startTime }} – {{ sess.endTime }}</td><td class="px-3 py-4 text-slate-600 dark:text-slate-300">{{ sess.instructor?.name || 'Not assigned' }}</td><td class="px-3 py-4"><UBadge color="primary" variant="subtle">{{ sess.stats?.present || 0 }} present / {{ sess.stats?.total || 0 }} students</UBadge></td><td class="px-3 py-4"><div class="flex justify-end gap-2"><UButton size="xs" color="primary" variant="soft" @click="selectSession(sess)">View attendance</UButton><UButton size="xs" color="error" variant="ghost" @click="deleteSession(sess.id)">Delete</UButton></div></td></tr></tbody></table></div></UCard>
    </template>
    <UCard v-if="selectedSession" class="mt-6"><template #header><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold">Attendance for {{ selectedSession.name || 'Class' }}</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">{{ formatDate(selectedSession.date) }} · {{ selectedSession.startTime }} – {{ selectedSession.endTime }}</p></div><div class="flex gap-2"><UButton size="sm" color="primary" variant="soft" @click="markAllPresent">Mark all present</UButton><UButton size="sm" color="neutral" variant="ghost" @click="selectedSession = null">Close</UButton></div></div></template><p v-if="loadingAttendance" class="text-sm text-slate-500">Loading student records...</p><div v-else class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="border-b border-slate-100 text-left text-xs uppercase tracking-wide text-slate-400 dark:border-slate-800"><tr><th class="px-3 py-3">Student</th><th class="w-48 px-3 py-3">Status</th><th class="px-3 py-3">Notes</th></tr></thead><tbody><tr v-for="item in attendanceItems" :key="item.studentId" class="border-b border-slate-100 last:border-0 dark:border-slate-800"><td class="px-3 py-3 font-medium">{{ item.firstName }} {{ item.lastName }}</td><td class="w-48 px-3 py-3"><USelect v-model="item.status" :items="statusOptions" variant="ghost" size="sm" class="w-44" /></td><td class="px-3 py-3"><UInput v-model="item.notes" placeholder="Optional note" size="sm" /></td></tr></tbody></table><div class="mt-4 flex justify-end"><UButton :loading="savingAttendance" @click="saveAttendance">Save attendance</UButton></div></div></UCard>
  </div>
</template>
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const toast = useToast()
const dojos = ref<any[]>([]); const schedules = ref<any[]>([]); const instructors = ref<any[]>([]); const selectedDojoId = ref<number | null>(null); const sessions = ref<any[]>([]); const loadingSessions = ref(false); const creatingSession = ref(false); const showSessionForm = ref(false)
const selectedSession = ref<any>(null); const attendanceItems = ref<any[]>([]); const loadingAttendance = ref(false); const savingAttendance = ref(false)
const today = new Date().toISOString().slice(0, 10); const newSessionDate = ref(today); const selectedScheduleId = ref<number | null>(null); const newSessionStart = ref(''); const newSessionEnd = ref(''); const newSessionName = ref(''); const newSessionInstructorId = ref<number | null>(null)
const dojoOptions = computed(() => dojos.value.map(dojo => ({ label: dojo.name, value: dojo.id }))); const selectedDojo = computed(() => dojos.value.find(dojo => dojo.id === selectedDojoId.value)); const totalPresent = computed(() => sessions.value.reduce((sum, session) => sum + (session.stats?.present || 0), 0)); const summary = computed(() => [{ label: 'Selected dojo', value: selectedDojo.value?.name || '—' }, { label: 'Class sessions', value: sessions.value.length }, { label: 'Present in all sessions', value: totalPresent.value }]); const scheduleOptions = computed(() => schedules.value.map(schedule => ({ label: `${getDayName(schedule.dayOfWeek)} ${schedule.startTime}–${schedule.endTime} ${schedule.name || ''}`, value: schedule.id }))); const instructorOptions = computed(() => instructors.value.map(user => ({ label: user.name, value: user.id }))); const statusOptions = [{ label: 'Present', value: 'present' }, { label: 'Absent', value: 'absent' }, { label: 'Late', value: 'late' }, { label: 'Excused', value: 'excused' }, { label: 'Unmarked', value: 'unmarked' }]
function getDayName(day: number) { return ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][day] || '' }; function formatDate(timestamp: number) { return new Date(timestamp).toLocaleDateString() }
async function loadDojosAndInstructors() { try { const [dojoData, userData] = await Promise.all([$fetch<any[]>('/api/dojos'), $fetch<any[]>('/api/users')]); dojos.value = dojoData; instructors.value = userData.filter(user => ['owner', 'admin', 'instructor', 'dojo_head'].includes(user.role)) } catch (error: any) { toast.add({ color: 'error', title: 'Could not load attendance', description: error.message }) } }
async function onDojoChange() { selectedSession.value = null; sessions.value = []; showSessionForm.value = false; selectedScheduleId.value = null; newSessionStart.value = ''; newSessionEnd.value = ''; newSessionName.value = ''; newSessionInstructorId.value = null; if (!selectedDojoId.value) return; try { schedules.value = await $fetch(`/api/dojos/${selectedDojoId.value}/schedules`) } catch (error: any) { toast.add({ color: 'error', title: 'Could not load class times', description: error.message }) }; await loadSessions() }
async function loadSessions() { if (!selectedDojoId.value) return; loadingSessions.value = true; try { sessions.value = await $fetch(`/api/dojos/${selectedDojoId.value}/sessions`) } catch (error: any) { toast.add({ color: 'error', title: 'Could not load class sessions', description: error.message }) } finally { loadingSessions.value = false } }
function autoFillFromSchedule() { const schedule = schedules.value.find(item => item.id === selectedScheduleId.value); if (schedule) { newSessionStart.value = schedule.startTime; newSessionEnd.value = schedule.endTime; newSessionName.value = schedule.name || ''; newSessionInstructorId.value = schedule.instructorId || null } }
async function createSession() { if (!selectedDojoId.value || !newSessionDate.value || !newSessionStart.value || !newSessionEnd.value) { toast.add({ color: 'warning', title: 'Choose a date, start time, and end time' }); return }; creatingSession.value = true; try { await $fetch(`/api/dojos/${selectedDojoId.value}/sessions`, { method: 'POST', body: { date: newSessionDate.value, startTime: newSessionStart.value, endTime: newSessionEnd.value, name: newSessionName.value || undefined, instructorId: newSessionInstructorId.value || undefined, scheduleId: selectedScheduleId.value || undefined } }); toast.add({ color: 'success', title: 'Class session saved' }); newSessionDate.value = today; selectedScheduleId.value = null; newSessionStart.value = ''; newSessionEnd.value = ''; newSessionName.value = ''; newSessionInstructorId.value = null; showSessionForm.value = false; await loadSessions() } catch (error: any) { toast.add({ color: 'error', title: 'Could not save class session', description: error.message }) } finally { creatingSession.value = false } }
async function selectSession(session: any) { selectedSession.value = session; loadingAttendance.value = true; try { attendanceItems.value = (await $fetch<any>(`/api/sessions/${session.id}/attendance`)).attendance } catch (error: any) { toast.add({ color: 'error', title: 'Could not load student records', description: error.message }) } finally { loadingAttendance.value = false } }
function markAllPresent() { attendanceItems.value.forEach(item => { item.status = 'present' }) }
async function saveAttendance() { if (!selectedSession.value) return; savingAttendance.value = true; try { await $fetch(`/api/sessions/${selectedSession.value.id}/attendance`, { method: 'POST', body: { items: attendanceItems.value.map(item => ({ studentId: item.studentId, status: item.status, notes: item.notes || undefined, attendanceId: item.attendanceId })) } }); toast.add({ color: 'success', title: 'Attendance saved' }); await loadSessions(); await selectSession(selectedSession.value) } catch (error: any) { toast.add({ color: 'error', title: 'Could not save attendance', description: error.message }) } finally { savingAttendance.value = false } }
async function deleteSession(sessionId: number) { if (!confirm('Delete this class session and its attendance records?')) return; try { await $fetch(`/api/dojos/${selectedDojoId.value}/sessions/${sessionId}`, { method: 'DELETE' }); toast.add({ color: 'success', title: 'Class session deleted' }); if (selectedSession.value?.id === sessionId) selectedSession.value = null; await loadSessions() } catch (error: any) { toast.add({ color: 'error', title: 'Could not delete class session', description: error.message }) } }
onMounted(loadDojosAndInstructors)
</script>
