<template>
  <div class="mx-auto max-w-7xl"><section class="mb-6"><p class="text-sm font-semibold text-primary">INSIGHTS</p><h2 class="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Certificates awarded</h2><p class="mt-2 text-sm text-slate-500">Track issued student grading and tournament certificates across your organization.</p></section><UCard><div class="grid gap-3 md:grid-cols-4"><USelect v-model="hierarchyId" :items="hierarchyOptions" placeholder="All hierarchy" /><USelect v-model="dojoId" :items="dojoOptions" placeholder="All dojos" /><USelect v-model="type" :items="typeOptions" /><UInput v-model="search" icon="i-lucide-search" placeholder="Search student or certificate" /></div></UCard><UCard class="mt-6"><div v-if="pending" class="space-y-3"><USkeleton v-for="item in 6" :key="item" class="h-14" /></div><UAlert v-else-if="error" color="error" title="Could not load certificates" description="Please try again." /><div v-else-if="certificates?.length" class="overflow-x-auto"><table class="min-w-[900px] text-sm"><thead class="border-b border-slate-100 text-left text-xs uppercase tracking-wide text-slate-400 dark:border-slate-800"><tr><th class="px-3 py-3">Student</th><th class="px-3 py-3">Certificate</th><th class="px-3 py-3">Dojo</th><th class="px-3 py-3">Issued</th><th class="px-3 py-3">Number</th><th class="px-3 py-3 text-right">File</th></tr></thead><tbody><tr v-for="certificate in certificates" :key="certificate.id" class="border-b border-slate-100 last:border-0 dark:border-slate-800"><td class="px-3 py-4"><NuxtLink :to="`/students/${certificate.studentId}`" class="font-medium hover:text-primary">{{ certificate.studentName }}</NuxtLink></td><td class="px-3 py-4"><p class="font-medium">{{ certificate.title }}</p><p class="mt-1 text-xs text-slate-400">{{ certificate.typeLabel }}<span v-if="certificate.details"> · {{ certificate.details }}</span></p></td><td class="px-3 py-4">{{ certificate.dojoName }}</td><td class="px-3 py-4">{{ formatDate(certificate.issuedAt) }}</td><td class="px-3 py-4">{{ certificate.certificateNumber || '—' }}</td><td class="px-3 py-4 text-right"><UButton v-if="certificate.certificateUrl" :href="certificate.certificateUrl" target="_blank" size="xs" color="primary" variant="soft" icon="i-lucide-download">Open</UButton><span v-else class="text-slate-400">No file</span></td></tr></tbody></table></div><div v-else class="py-12 text-center text-sm text-slate-500">No certificates match these filters.</div></UCard></div>
</template>
<script setup lang="ts">
definePageMeta({ middleware: ['auth', 'admin'] })
const hierarchyId = ref<number | null>(null); const dojoId = ref<number | null>(null); const type = ref('all'); const search = ref('')
const { data: scope } = await useFetch<any>('/api/reports/scope')
const hierarchyOptions = computed(() => [{ label: 'All hierarchy', value: null }, ...((scope.value?.nodes || []).map((node: any) => ({ label: node.label || node.name, value: node.id })))]); const dojoOptions = computed(() => [{ label: 'All dojos', value: null }, ...((scope.value?.dojos || []).map((dojo: any) => ({ label: dojo.name, value: dojo.id })))]); const typeOptions = [{ label: 'All certificate types', value: 'all' }, { label: 'Grading certificates', value: 'grading' }, { label: 'Tournament certificates', value: 'achievement' }]
const url = computed(() => `/api/certificates?${new URLSearchParams({ ...(hierarchyId.value ? { hierarchyId: String(hierarchyId.value) } : {}), ...(dojoId.value ? { dojoId: String(dojoId.value) } : {}), type: type.value, ...(search.value ? { search: search.value } : {}) }).toString()}`); const { data: certificates, pending, error } = await useFetch<any[]>(url); function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) }
</script>
