<template>
  <div class="mx-auto max-w-7xl">
    <section class="mb-6 flex flex-wrap items-end justify-between gap-4">
      <div><p class="text-sm font-semibold text-primary">OPERATIONS</p><h2 class="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Grading exams</h2><p class="mt-2 text-sm text-slate-500">Schedule gradings, assign students, and record their results.</p></div>
      <UButton icon="i-lucide-calendar-plus" @click="showForm = !showForm">Schedule grading</UButton>
    </section>

    <UCard v-if="showForm" class="mb-6">
      <form class="grid gap-4 md:grid-cols-2" @submit.prevent="createExam">
        <UFormField label="Dojos" required class="md:col-span-2"><p class="mb-2 text-xs text-slate-500">Select one or several dojos. Each receives its own exam list.</p><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><UCheckbox v-for="dojo in dojos || []" :key="dojo.id" :model-value="form.dojoIds.includes(dojo.id)" :label="dojo.name" @update:model-value="toggleDojo(dojo.id, $event)" /></div></UFormField>
        <UFormField label="Exam name" required><UInput v-model="form.name" /></UFormField>
        <UFormField label="Exam date" required><UInput v-model="form.scheduledAt" type="date" /></UFormField>
        <div class="flex justify-end gap-2 md:col-span-2"><UButton color="neutral" variant="ghost" @click="showForm = false">Cancel</UButton><UButton type="submit" :loading="saving">Create exams</UButton></div>
      </form>
    </UCard>

    <UCard v-if="editingId" class="mb-6">
      <template #header><div class="flex justify-between"><div><h3 class="font-semibold">Edit grading exam</h3><p class="text-sm text-slate-500">The dojo cannot be changed after creation.</p></div><UButton size="xs" color="neutral" variant="ghost" @click="cancelEdit">Close</UButton></div></template>
      <form class="grid gap-4 md:grid-cols-2" @submit.prevent="saveEdit"><UFormField label="Exam name" required><UInput v-model="editForm.name" /></UFormField><UFormField label="Exam date" required><UInput v-model="editForm.scheduledAt" type="date" /></UFormField><UFormField label="Status"><USelect v-model="editForm.status" :items="statusOptions" /></UFormField><div class="flex justify-end gap-2 md:col-span-2"><UButton color="neutral" variant="ghost" @click="cancelEdit">Cancel</UButton><UButton type="submit" :loading="savingEdit">Save changes</UButton></div></form>
    </UCard>

    <div v-if="pending" class="space-y-3"><USkeleton v-for="i in 3" :key="i" class="h-40" /></div>
    <div v-else-if="!exams?.length" class="py-14 text-center text-slate-500">No grading exams scheduled yet.</div>
    <div v-else class="space-y-5">
      <UCard v-for="exam in exams" :key="exam.id">
        <template #header><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold">{{ exam.name }}</h3><p class="mt-1 text-sm text-slate-500">{{ exam.dojo?.name }} · {{ formatDate(exam.scheduledAt) }}</p></div><div class="flex gap-1"><UBadge color="primary" variant="subtle">{{ exam.status }}</UBadge><UButton size="xs" color="neutral" variant="soft" icon="i-lucide-pencil" @click="startEdit(exam)">Edit</UButton><UButton size="xs" color="error" variant="ghost" icon="i-lucide-trash-2" @click="deleteExam(exam)">Delete</UButton></div></div></template>
        <form class="mb-4 flex flex-wrap gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-800" @submit.prevent="addCandidate(exam)"><USelect v-model="candidate[exam.id]" :items="studentOptions(exam.dojoId, exam.attempts)" placeholder="Student" class="min-w-52 flex-1" /><USelect v-model="candidateRank[exam.id]" :items="rankOptions" placeholder="Target rank" class="min-w-48" /><UInput v-model.number="candidateFee[exam.id]" type="number" min="0" placeholder="Fee (smallest unit)" class="min-w-44" /><UButton type="submit" size="sm">Assign student</UButton></form>
        <div v-if="exam.attempts.length" class="overflow-x-auto"><table class="min-w-[1100px] w-full text-sm"><thead class="border-b text-left text-xs uppercase tracking-wide text-slate-400"><tr><th class="p-2">Student</th><th class="p-2">Rank</th><th class="p-2">Appearance</th><th class="p-2">Fee</th><th class="p-2">Payment</th><th class="p-2">Method</th><th class="p-2">Result</th><th class="p-2"></th></tr></thead><tbody><tr v-for="attempt in exam.attempts" :key="attempt.id" class="border-b border-slate-100 dark:border-slate-800"><td class="p-2 font-medium">{{ attempt.student.firstName }} {{ attempt.student.lastName }}</td><td class="p-2"><USelect :model-value="attempt.targetBeltRankId" :items="rankOptions" size="xs" @update:model-value="updateAttempt(exam.id, attempt.id, { targetBeltRankId: $event })" /></td><td class="p-2"><USelect :model-value="attempt.attendanceStatus" :items="attendanceOptions" size="xs" @update:model-value="updateAttempt(exam.id, attempt.id, { attendanceStatus: $event })" /></td><td class="p-2"><UInput :model-value="attempt.feeAmount" type="number" min="0" size="xs" @update:model-value="updateAttempt(exam.id, attempt.id, { feeAmount: Number($event) })" /></td><td class="p-2"><USelect :model-value="attempt.paymentStatus" :items="paymentStatusOptions" size="xs" @update:model-value="updateAttempt(exam.id, attempt.id, { paymentStatus: $event })" /></td><td class="p-2"><USelect :model-value="attempt.paymentMethod || 'cash'" :items="paymentMethodOptions" size="xs" @update:model-value="updateAttempt(exam.id, attempt.id, { paymentMethod: $event })" /></td><td class="p-2"><USelect :model-value="attempt.result" :items="resultOptions" size="xs" @update:model-value="updateAttempt(exam.id, attempt.id, { result: $event })" /></td><td class="p-2 text-right"><div class="flex justify-end gap-1"><UButton v-if="attempt.result === 'passed' && ['paid','waived'].includes(attempt.paymentStatus) && !attempt.gradingId" size="xs" @click="award(exam.id, attempt.id)">Award</UButton><UBadge v-else-if="attempt.gradingId" color="success" variant="subtle">Awarded</UBadge><UButton v-if="!attempt.gradingId" size="xs" color="error" variant="ghost" icon="i-lucide-user-minus" @click="deleteCandidate(exam.id, attempt)">Remove</UButton></div></td></tr></tbody></table></div>
      </UCard>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const toast = useToast(); const showForm = ref(false); const saving = ref(false); const savingEdit = ref(false); const editingId = ref<number | null>(null)
const candidate = reactive<Record<number, number | undefined>>({}); const candidateRank = reactive<Record<number, number | undefined>>({}); const candidateFee = reactive<Record<number, number | undefined>>({})
const { data: exams, pending, refresh } = await useFetch<any[]>('/api/grading-exams'); const { data: dojos } = await useFetch<any[]>('/api/dojos'); const { data: students } = await useFetch<any[]>('/api/students'); const { data: ranks } = await useFetch<any[]>('/api/belt-ranks')
const form = reactive({ dojoIds: [] as number[], name: '', scheduledAt: '' }); const editForm = reactive({ name: '', scheduledAt: '', status: 'open' })
const rankOptions = computed(() => (ranks.value || []).map(rank => ({ label: rank.name, value: rank.id }))); const statusOptions = ['draft', 'open', 'completed', 'cancelled'].map(value => ({ label: value, value })); const attendanceOptions = ['registered', 'appeared', 'absent', 'withdrawn'].map(value => ({ label: value, value })); const paymentStatusOptions = ['pending', 'paid', 'waived', 'refunded'].map(value => ({ label: value, value })); const paymentMethodOptions = ['cash', 'bank_transfer', 'card', 'other'].map(value => ({ label: value.replace('_', ' '), value })); const dateValue = (value: string) => new Date(value).toISOString().slice(0, 10); const formatDate = (value: string) => new Date(value).toLocaleDateString('en-IN', { dateStyle: 'medium' })
function toggleDojo(id: number, checked: boolean) { form.dojoIds = checked ? [...new Set([...form.dojoIds, id])] : form.dojoIds.filter(dojoId => dojoId !== id) }
const studentOptions = (dojoId: number, attempts: any[]) => (students.value || []).filter(s => s.dojoId === dojoId && !attempts.some(a => a.studentId === s.id)).map(s => ({ label: `${s.firstName} ${s.lastName}`, value: s.id }))
async function createExam() { if (!form.dojoIds.length || !form.name || !form.scheduledAt) { toast.add({ title: 'Select at least one dojo and an exam date', color: 'warning' }); return }; saving.value = true; try { await $fetch('/api/grading-exams', { method: 'POST', body: form }); showForm.value = false; Object.assign(form, { dojoIds: [], name: '', scheduledAt: '' }); await refresh(); toast.add({ title: 'Grading exams scheduled', color: 'success' }) } catch (error: any) { toast.add({ title: 'Could not schedule exam', description: error.data?.statusMessage || error.message, color: 'error' }) } finally { saving.value = false } }
function startEdit(exam: any) { editingId.value = exam.id; Object.assign(editForm, { name: exam.name, scheduledAt: dateValue(exam.scheduledAt), status: exam.status }); window.scrollTo({ top: 0, behavior: 'smooth' }) }; function cancelEdit() { editingId.value = null }
async function saveEdit() { if (!editingId.value) return; savingEdit.value = true; try { await $fetch(`/api/grading-exams/${editingId.value}`, { method: 'PATCH', body: editForm }); cancelEdit(); await refresh(); toast.add({ title: 'Grading exam updated', color: 'success' }) } catch (error: any) { toast.add({ title: 'Could not update exam', description: error.data?.statusMessage, color: 'error' }) } finally { savingEdit.value = false } }
async function deleteExam(exam: any) { if (!confirm(`Delete ${exam.name} for ${exam.dojo?.name}? Its unawarded candidates will also be removed.`)) return; try { await $fetch(`/api/grading-exams/${exam.id}`, { method: 'DELETE' }); await refresh(); toast.add({ title: 'Grading exam deleted', color: 'success' }) } catch (error: any) { toast.add({ title: 'Could not delete exam', description: error.data?.statusMessage, color: 'error' }) } }
async function addCandidate(exam: any) { if (!candidate[exam.id] || candidateFee[exam.id] === undefined) { toast.add({ title: 'Select a student and enter their fee', color: 'warning' }); return }; try { await $fetch(`/api/grading-exams/${exam.id}/attempts`, { method: 'POST', body: { studentId: candidate[exam.id], targetBeltRankId: candidateRank[exam.id], feeAmount: candidateFee[exam.id] } }); candidate[exam.id] = undefined; candidateRank[exam.id] = undefined; candidateFee[exam.id] = undefined; await refresh() } catch (error: any) { toast.add({ title: 'Could not assign student', description: error.data?.statusMessage, color: 'error' }) } }
async function updateAttempt(examId: number, attemptId: number, body: any) { try { await $fetch(`/api/grading-exams/${examId}/attempts/${attemptId}`, { method: 'PATCH', body }); await refresh() } catch { toast.add({ title: 'Could not update candidate', color: 'error' }) } }
async function deleteCandidate(examId: number, attempt: any) { if (!confirm(`Remove ${attempt.student.firstName} ${attempt.student.lastName} from this grading?`)) return; try { await $fetch(`/api/grading-exams/${examId}/attempts/${attempt.id}`, { method: 'DELETE' }); await refresh(); toast.add({ title: 'Student removed from grading', color: 'success' }) } catch (error: any) { toast.add({ title: 'Could not remove student', description: error.data?.statusMessage, color: 'error' }) } }
async function award(examId: number, attemptId: number) { try { await $fetch(`/api/grading-exams/${examId}/attempts/${attemptId}/award`, { method: 'POST' }); await refresh(); toast.add({ title: 'Promotion awarded', color: 'success' }) } catch (error: any) { toast.add({ title: 'Could not award promotion', description: error.data?.statusMessage, color: 'error' }) } }
</script>
