<template>
  <div>
    <div class="mb-7"><div class="flex justify-between text-xs font-medium text-slate-500"><span>Set up your workspace</span><span>Step {{ step }} of {{ totalSteps }}</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-primary transition-all" :style="{ width: `${(step / totalSteps) * 100}%` }" /></div></div>
    <form class="space-y-6" enctype="multipart/form-data" @submit.prevent="next">
      <section v-if="step === 1"><p class="text-sm font-semibold text-primary">LET'S GET STARTED</p><h1 class="mt-2 text-2xl font-semibold">What is your organization called?</h1><div class="mt-6 space-y-4"><UFormField label="Organization name" required><UInput v-model="form.organizationName" autofocus required placeholder="Sunrise Karate Academy" /></UFormField><UFormField label="Workspace address" required help="Choose a short, unique address such as gojukai. This becomes your workspace URL."><UInput v-model="form.workspaceSlug" required placeholder="gojukai" autocapitalize="none" /></UFormField><UFormField label="Workspace plan" required help="Paid plans begin with a 14-day trial. You can also start on Free Forever."><USelect v-model="form.subscriptionPlan" :items="planOptions" /></UFormField></div></section>
      <section v-else-if="step === 2"><p class="text-sm font-semibold text-primary">YOUR MAIN LOCATION</p><h1 class="mt-2 text-2xl font-semibold">Where do you teach?</h1><p class="mt-2 text-sm text-slate-500">All fields below are required for student records, receipts, and organization reports.</p><div class="mt-6 grid gap-4 sm:grid-cols-2"><UFormField class="sm:col-span-2" label="Dojo name" required><UInput v-model="form.dojoName" autofocus required placeholder="Your main dojo" /></UFormField><UFormField class="sm:col-span-2" label="Street address" required><UInput v-model="form.dojoAddress" required placeholder="12 Main Street, Indiranagar" /></UFormField><UFormField label="City" required><UInput v-model="form.dojoCity" required placeholder="Bengaluru" /></UFormField><UFormField label="State / province" required><UInput v-model="form.dojoStateProvince" required placeholder="Karnataka" /></UFormField><UFormField class="sm:col-span-2" label="Country" required><UInput v-model="form.dojoCountry" required placeholder="India" /></UFormField></div></section>
      <section v-else-if="hierarchyStep && step === hierarchyStep"><p class="text-sm font-semibold text-primary">{{ form.subscriptionPlan === 'national' ? 'NATIONAL STRUCTURE' : 'STATE STRUCTURE' }}</p><h1 class="mt-2 text-2xl font-semibold">We will build your {{ form.subscriptionPlan === 'national' ? 'national' : 'state' }} hierarchy.</h1><p class="mt-2 text-sm text-slate-500">Country, state, and city come from your location details. Add optional levels below and we will create the structure for you.</p><div class="mt-6 grid gap-4 sm:grid-cols-2"><UFormField label="District (optional)"><UInput v-model="form.districtName" placeholder="e.g. Ahmedabad District" /></UFormField><UFormField label="Branch name (optional)" help="Leave blank to use your dojo name."><UInput v-model="form.branchName" placeholder="e.g. North Gujarat Branch" /></UFormField></div><div class="mt-5 rounded-2xl bg-primary/5 p-4 text-sm"><p class="font-medium">Your starter structure</p><p class="mt-1">{{ hierarchyPreview }}</p></div></section>
      <section v-else-if="step === programStep"><p class="text-sm font-semibold text-primary">WHAT YOU TEACH</p><h1 class="mt-2 text-2xl font-semibold">Which martial art do you teach?</h1><p class="mt-2 text-sm text-slate-500">Choose your discipline and style. If yours is not listed, add it in your own words.</p><div class="mt-6 space-y-4"><UFormField label="Martial art" required><USelect v-model="form.martialArt" :items="martialArtOptions" required placeholder="Select a martial art" /></UFormField><UFormField v-if="form.martialArt === 'custom'" label="Custom martial art" required><UInput v-model="form.customMartialArt" required placeholder="e.g. Kalaripayattu" /></UFormField><UFormField v-if="form.martialArt" label="Style or school" required><USelect v-model="form.style" :items="styleOptions" required placeholder="Select a style or school" /><UInput v-if="form.style === 'custom'" v-model="form.customStyle" required class="mt-2" placeholder="Enter your style or lineage" /></UFormField></div></section>
      <section v-else-if="step === 4"><p class="text-sm font-semibold text-primary">FEES</p><h1 class="mt-2 text-2xl font-semibold">Set your default student fee</h1><p class="mt-2 text-sm text-slate-500">New students at this dojo will receive this plan automatically.</p><div class="mt-6 grid gap-4 sm:grid-cols-2"><UFormField label="Fee plan name" required><UInput v-model="form.feeName" required /></UFormField><UFormField label="Amount (₹)" required><UInput v-model.number="form.feeAmount" required type="number" min="1" /></UFormField></div></section>
      <section v-else-if="step === 5"><p class="text-sm font-semibold text-primary">YOUR TEAM</p><h1 class="mt-2 text-2xl font-semibold">Add staff for this dojo <span class="text-slate-500">Optional</span></h1><template v-if="trialPlan"><p class="mt-2 text-sm text-slate-500">You create each staff member's temporary password and assign them to this location. They can change it after signing in.</p><div class="mt-6 space-y-4"><div v-for="(staff, index) in staffMembers" :key="index" class="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-2"><UInput v-model="staff.name" placeholder="Staff member name" /><UInput v-model="staff.email" type="email" placeholder="Email address" /><UInput v-model="staff.password" type="password" placeholder="Temporary password (8+ characters)" /><USelect v-model="staff.assignmentRole" :items="staffRoleOptions" /><UButton color="error" variant="ghost" class="sm:col-span-2 justify-self-start" @click="removeStaff(index)">Remove staff member</UButton></div><UButton type="button" variant="outline" icon="i-lucide-user-plus" @click="addStaff">Add staff member</UButton></div></template><div v-else class="mt-6 rounded-2xl bg-slate-100 p-4 text-sm text-slate-600">Free Forever includes your owner account. Choose a paid trial in Step 1 if you would like to invite staff now.</div></section>
      <section v-else-if="step === 6"><p class="text-sm font-semibold text-primary">WORKSPACE OWNER</p><h1 class="mt-2 text-2xl font-semibold">Who will own and manage this workspace?</h1><p class="mt-2 text-sm text-slate-500">This is your personal account name. It will appear as the workspace owner, separate from the organization name.</p><div class="mt-6 space-y-4"><UFormField label="Workspace owner name" required><UInput v-model="form.name" autofocus required placeholder="Your full name" /></UFormField><UFormField label="Owner email address" required><UInput v-model="form.email" required type="email" /></UFormField><UFormField label="Choose a password" required><UInput v-model="form.password" required type="password" /></UFormField></div></section>
      <section v-else><p class="text-sm font-semibold text-primary">ALMOST READY</p><h1 class="mt-2 text-2xl font-semibold">Add a logo? <span class="text-slate-500">Optional</span></h1><UFormField class="mt-6" label="Organization logo"><UInput type="file" accept="image/*" @change="onFileChange" /></UFormField><div class="mt-6 rounded-2xl bg-slate-100 p-4 text-sm"><p class="font-semibold">Your workspace will include</p><ul class="mt-2 space-y-1 text-slate-600"><li>Your organization and first dojo</li><li>A {{ martialArtLabel }} program and belt ranks</li><li>A default fee plan ready for enrolment</li></ul></div></section>
      <div class="flex justify-between gap-3 pt-2"><UButton v-if="step > 1" type="button" color="neutral" variant="ghost" @click="step--">Back</UButton><span v-else /><UButton type="submit" :loading="loading">{{ step === totalSteps ? 'Create my ready-to-use workspace' : 'Continue' }}</UButton></div>
    </form>
    <p class="mt-6 text-center text-sm text-slate-500">Already have an account? <NuxtLink to="/auth/login" class="font-medium text-primary">Sign in</NuxtLink></p>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'auth' })
const toast = useToast(); const route = useRoute(); const step = ref(1); const totalSteps = 7; const hierarchyStep = -1; const programStep = 3; const feeStep = 4; const staffStep = 5; const ownerStep = 6; const loading = ref(false); const logoFile = ref<File | null>(null)
const initialPlan = ['city-starter', 'city-pro', 'state-pro', 'national'].includes(String(route.query.trialPlan)) ? String(route.query.trialPlan) : 'free'
const form = reactive({ organizationName: '', workspaceSlug: '', dojoName: '', dojoAddress: '', dojoCity: '', dojoStateProvince: '', dojoCountry: '', dojoPhone: '', dojoEmail: '', districtName: '', branchName: '', feeName: 'Monthly tuition', feeAmount: null as number | null, name: '', email: '', password: '', martialArt: '', style: '', customMartialArt: '', customStyle: '', subscriptionPlan: initialPlan })
const planOptions = [
  { label: 'Free Forever — one owner, one dojo, up to 25 students', value: 'free' },
  { label: 'City Starter — two dojos in one city, staff, 75 students per dojo', value: 'city-starter' },
  { label: 'City Pro — unlimited dojos, staff, and students in one city', value: 'city-pro' },
  { label: 'State Pro — unlimited locations, staff, and students in one state', value: 'state-pro' },
  { label: 'National — unlimited locations, staff, and students in one country', value: 'national' },
]
const trialPlan = computed(() => form.subscriptionPlan === 'free' ? null : form.subscriptionPlan); const billingPeriod = computed(() => route.query.billingPeriod === 'monthly' ? 'monthly' : 'annual')
const isAdvancedPlan = computed(() => ['state-pro', 'national'].includes(form.subscriptionPlan))
const hierarchyPreview = computed(() => { const district = form.districtName.trim() ? ` → ${form.districtName.trim()}` : ''; const branch = form.branchName.trim() || form.dojoName.trim() || 'Your dojo'; return form.subscriptionPlan === 'national' ? `${form.dojoCountry || 'Country'} → ${form.dojoStateProvince || 'State'}${district} → ${form.dojoCity || 'City'} → ${branch}` : `${form.dojoStateProvince || 'State'}${district} → ${form.dojoCity || 'City'} → ${branch}` })
const martialArtOptions = [
  { label: 'Aikido', value: 'aikido' }, { label: 'Brazilian Jiu-Jitsu', value: 'bjj' }, { label: 'Boxing', value: 'boxing' }, { label: 'Capoeira', value: 'capoeira' },
  { label: 'Eskrima / Arnis / Kali', value: 'eskrima' }, { label: 'Hapkido', value: 'hapkido' }, { label: 'Iaido', value: 'iaido' }, { label: 'Jeet Kune Do', value: 'jkd' },
  { label: 'Judo', value: 'judo' }, { label: 'Jujutsu / Japanese Jiu-Jitsu', value: 'jujutsu' }, { label: 'Kalaripayattu', value: 'kalaripayattu' }, { label: 'Karate', value: 'karate' },
  { label: 'Kenjutsu', value: 'kenjutsu' }, { label: 'Kendo', value: 'kendo' }, { label: 'Kickboxing', value: 'kickboxing' }, { label: 'Krav Maga', value: 'krav_maga' },
  { label: 'Kung Fu / Wushu', value: 'kung_fu' }, { label: 'Mixed Martial Arts (MMA)', value: 'mma' }, { label: 'Muay Thai', value: 'muay_thai' }, { label: 'Pencak Silat', value: 'silat' },
  { label: 'Sambo', value: 'sambo' }, { label: 'Savate', value: 'savate' }, { label: 'Sumo', value: 'sumo' }, { label: 'Taekwondo', value: 'taekwondo' },
  { label: 'Tai Chi / Taijiquan', value: 'tai_chi' }, { label: 'Tang Soo Do', value: 'tang_soo_do' }, { label: 'Wrestling', value: 'wrestling' }, { label: 'Wing Chun', value: 'wing_chun' },
  { label: 'Other martial art', value: 'custom' },
]
const stylesByMartialArt: Record<string, Array<{ label: string, value: string }>> = {
  aikido: [{ label: 'Aikikai', value: 'aikikai' }, { label: 'Iwama-ryu', value: 'iwama_ryu' }, { label: 'Ki Aikido (Shin Shin Toitsu)', value: 'ki_aikido' }, { label: 'Yoshinkan', value: 'yoshinkan' }],
  bjj: [{ label: 'Brazilian Jiu-Jitsu', value: 'brazilian_jiu_jitsu' }, { label: 'Gracie Jiu-Jitsu', value: 'gracie_jiu_jitsu' }, { label: '10th Planet Jiu-Jitsu', value: '10th_planet' }],
  boxing: [{ label: 'Western boxing', value: 'western_boxing' }, { label: 'Bare-knuckle boxing', value: 'bare_knuckle' }],
  capoeira: [{ label: 'Angola', value: 'angola' }, { label: 'Regional', value: 'regional' }, { label: 'Contemporânea', value: 'contemporanea' }],
  eskrima: [{ label: 'Arnis', value: 'arnis' }, { label: 'Balintawak', value: 'balintawak' }, { label: 'Doce Pares', value: 'doce_pares' }, { label: 'Kali', value: 'kali' }, { label: 'Modern Arnis', value: 'modern_arnis' }, { label: 'Pekiti-Tirsia', value: 'pekiti_tirsia' }, { label: 'Sayoc Kali', value: 'sayoc_kali' }],
  hapkido: [{ label: 'Traditional Hapkido', value: 'traditional_hapkido' }, { label: 'Combat Hapkido', value: 'combat_hapkido' }, { label: 'Kuk Sool Won', value: 'kuk_sool_won' }],
  iaido: [{ label: 'Muso Jikiden Eishin-ryu', value: 'muso_jikiden_eishin_ryu' }, { label: 'Muso Shinden-ryu', value: 'muso_shinden_ryu' }, { label: 'Seitei Iaido', value: 'seitei_iaido' }],
  jkd: [{ label: 'Jun Fan Jeet Kune Do', value: 'jun_fan' }, { label: 'Jeet Kune Do Concepts', value: 'jkd_concepts' }],
  judo: [{ label: 'Kodokan Judo', value: 'kodokan' }, { label: 'Kosen Judo', value: 'kosen' }],
  jujutsu: [{ label: 'Daito-ryu', value: 'daito_ryu' }, { label: 'Hakko-ryu', value: 'hakko_ryu' }, { label: 'Shorinji Kempo', value: 'shorinji_kempo' }, { label: 'Traditional Jujutsu', value: 'traditional_jujutsu' }],
  kalaripayattu: [{ label: 'Northern Kalari', value: 'northern_kalari' }, { label: 'Southern Kalari', value: 'southern_kalari' }],
  karate: [{ label: 'Goju-ryu', value: 'goju_ryu' }, { label: 'Kyokushin', value: 'kyokushin' }, { label: 'Shito-ryu', value: 'shito_ryu' }, { label: 'Shorin-ryu', value: 'shorin_ryu' }, { label: 'Shotokan', value: 'shotokan' }, { label: 'Uechi-ryu', value: 'uechi_ryu' }, { label: 'Wado-ryu', value: 'wado_ryu' }, { label: 'Isshin-ryu', value: 'isshin_ryu' }, { label: 'American Kenpo', value: 'american_kenpo' }],
  kenjutsu: [{ label: 'Kashima Shin-ryu', value: 'kashima_shin_ryu' }, { label: 'Katori Shinto-ryu', value: 'katori_shinto_ryu' }, { label: 'Niten Ichi-ryu', value: 'niten_ichi_ryu' }],
  kendo: [{ label: 'All Japan Kendo Federation', value: 'ajkf_kendo' }, { label: 'Sport Kendo', value: 'sport_kendo' }],
  kickboxing: [{ label: 'American Kickboxing', value: 'american_kickboxing' }, { label: 'Dutch Kickboxing', value: 'dutch_kickboxing' }, { label: 'Japanese Kickboxing', value: 'japanese_kickboxing' }, { label: 'K-1 Rules', value: 'k1_rules' }],
  krav_maga: [{ label: 'Civilian Krav Maga', value: 'civilian_krav_maga' }, { label: 'IKMF', value: 'ikmf' }, { label: 'KMG', value: 'kmg' }],
  kung_fu: [{ label: 'Bajiquan', value: 'bajiquan' }, { label: 'Choy Li Fut', value: 'choy_li_fut' }, { label: 'Hung Gar', value: 'hung_gar' }, { label: 'Northern Shaolin', value: 'northern_shaolin' }, { label: 'Praying Mantis', value: 'praying_mantis' }, { label: 'Sanda / Sanshou', value: 'sanda' }, { label: 'Shaolin Kung Fu', value: 'shaolin' }, { label: 'Wushu (modern)', value: 'modern_wushu' }, { label: 'Xingyiquan', value: 'xingyiquan' }],
  mma: [{ label: 'Mixed Martial Arts', value: 'mixed_martial_arts' }, { label: 'Combat Sambo MMA', value: 'combat_sambo_mma' }],
  muay_thai: [{ label: 'Muay Boran', value: 'muay_boran' }, { label: 'Muay Chaiya', value: 'muay_chaiya' }, { label: 'Muay Thai', value: 'muay_thai' }],
  silat: [{ label: 'Cimande', value: 'cimande' }, { label: 'Harimau', value: 'harimau' }, { label: 'Mande Muda', value: 'mande_muda' }, { label: 'Tapak Suci', value: 'tapak_suci' }],
  sambo: [{ label: 'Combat Sambo', value: 'combat_sambo' }, { label: 'Sport Sambo', value: 'sport_sambo' }],
  savate: [{ label: 'Assaut', value: 'assaut' }, { label: 'Combat Savate', value: 'combat_savate' }, { label: 'Savate Défense', value: 'savate_defense' }],
  sumo: [{ label: 'Amateur Sumo', value: 'amateur_sumo' }, { label: 'Professional Sumo', value: 'professional_sumo' }],
  taekwondo: [{ label: 'Chang Hon (ITF)', value: 'chang_hon_itf' }, { label: 'Kukkiwon / WT', value: 'kukkiwon_wt' }, { label: 'Songahm (ATA)', value: 'songahm_ata' }, { label: 'Tang Soo Do', value: 'tang_soo_do' }],
  tai_chi: [{ label: 'Chen style', value: 'chen' }, { label: 'Sun style', value: 'sun' }, { label: 'Wu style', value: 'wu' }, { label: 'Yang style', value: 'yang' }],
  tang_soo_do: [{ label: 'Moo Duk Kwan', value: 'moo_duk_kwan' }, { label: 'World Tang Soo Do', value: 'world_tang_soo_do' }],
  wrestling: [{ label: 'Freestyle wrestling', value: 'freestyle' }, { label: 'Greco-Roman wrestling', value: 'greco_roman' }, { label: 'Folkstyle wrestling', value: 'folkstyle' }, { label: 'Catch wrestling', value: 'catch_wrestling' }],
  wing_chun: [{ label: 'Ip Man lineage', value: 'ip_man' }, { label: 'Leung Ting', value: 'leung_ting' }, { label: 'Traditional Wing Chun', value: 'traditional_wing_chun' }],
}
const customStyleOption = { label: 'Other / custom style', value: 'custom' }
const styleOptions = computed(() => [...(stylesByMartialArt[form.martialArt] || []), customStyleOption])
const martialArtLabel = computed(() => form.martialArt === 'custom' ? (form.customMartialArt.trim() || 'martial art') : martialArtOptions.find(item => item.value === form.martialArt)?.label || 'martial art')
const staffMembers = ref<Array<{ name: string, email: string, password: string, assignmentRole: 'instructor' | 'dojo_head' }>>([]); const staffRoleOptions = [{ label: 'Instructor', value: 'instructor' }, { label: 'Dojo manager', value: 'dojo_head' }]
watch(() => form.martialArt, () => { form.style = ''; form.customStyle = '' })
function onFileChange(event: Event) { logoFile.value = (event.target as HTMLInputElement).files?.[0] || null }
function addStaff() { staffMembers.value.push({ name: '', email: '', password: '', assignmentRole: 'instructor' }) }; function removeStaff(index: number) { staffMembers.value.splice(index, 1) }
function validStep() { if (step.value === 1 && (!form.organizationName.trim() || !form.workspaceSlug.trim())) return 'Enter your organization name and workspace address.'; if (step.value === 2 && (!form.dojoName.trim() || !form.dojoAddress.trim() || !form.dojoCity.trim() || !form.dojoStateProvince.trim() || !form.dojoCountry.trim())) return 'Enter your dojo name and complete address.'; if (step.value === 3 && !form.martialArt) return 'Select the martial art you teach.'; if (step.value === 3 && form.martialArt === 'custom' && !form.customMartialArt.trim()) return 'Enter your martial art.'; if (step.value === 3 && !form.style) return 'Select your style or school.'; if (step.value === 3 && form.style === 'custom' && !form.customStyle.trim()) return 'Enter your style or lineage.'; if (step.value === 4 && (!form.feeName.trim() || !form.feeAmount || form.feeAmount < 1)) return 'Enter a fee plan name and amount.'; if (step.value === 5 && trialPlan.value && staffMembers.value.some(staff => !staff.name.trim() || !/^\S+@\S+\.\S+$/.test(staff.email) || staff.password.length < 8)) return 'Each staff member needs a name, valid email, and temporary password of at least 8 characters.'; if (step.value === 6) { if (!form.name.trim()) return 'Enter your name.'; if (!/^\S+@\S+\.\S+$/.test(form.email)) return 'Enter a valid email address.'; if (form.password.length < 8) return 'Choose a password with at least 8 characters.' }; return null }
async function next() { const message = validStep(); if (message) { toast.add({ color: 'warning', title: message }); return }; if (step.value < totalSteps) { step.value++; return }; loading.value = true; try { const fd = new FormData(); for (const [key, value] of Object.entries(form)) fd.append(key, String(value ?? '')); fd.set('martialArt', form.martialArt === 'custom' ? form.customMartialArt.trim() : form.martialArt); fd.set('style', form.style === 'custom' ? form.customStyle.trim() : form.style); fd.append('staff', JSON.stringify(staffMembers.value)); if (trialPlan.value) { fd.append('trialPlan', trialPlan.value); fd.append('billingPeriod', billingPeriod.value) }; if (logoFile.value) fd.append('logo', logoFile.value); const response = await $fetch<any>('/api/onboarding', { method: 'POST', body: fd }); if (response.workspaceUrl) { window.location.assign(`${response.workspaceUrl}/auth/login?created=1&email=${encodeURIComponent(form.email)}`); return }; await navigateTo({ path: '/auth/login', query: { created: '1', email: form.email } }) } catch (error: any) { toast.add({ color: 'error', title: 'We could not create your workspace', description: error.data?.statusMessage || error.message }) } finally { loading.value = false } }
</script>
