<template>
  <div>
    <div class="mb-7"><div class="flex justify-between text-xs font-medium text-slate-500"><span>Set up your workspace</span><span>Step {{ step }} of {{ totalSteps }}</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-primary transition-all" :style="{ width: `${(step / totalSteps) * 100}%` }" /></div></div>
    <form class="space-y-6" enctype="multipart/form-data" @submit.prevent="next">
      <section v-if="step === 1"><p class="text-sm font-semibold text-primary">LET'S GET STARTED</p><h1 class="mt-2 text-2xl font-semibold">What is your organization called?</h1><div class="mt-6 space-y-4"><UFormField label="Organization name"><UInput v-model="form.organizationName" autofocus placeholder="Sunrise Karate Academy" /></UFormField><UFormField label="Workspace address (optional)" help="Use a short, unique name such as gojukai. Leave blank to create one from your organization name."><UInput v-model="form.workspaceSlug" placeholder="gojukai" autocapitalize="none" /></UFormField></div></section>
      <section v-else-if="step === 2"><p class="text-sm font-semibold text-primary">YOUR MAIN LOCATION</p><h1 class="mt-2 text-2xl font-semibold">Where do you teach?</h1><div class="mt-6 space-y-4"><UFormField label="Dojo name"><UInput v-model="form.dojoName" autofocus placeholder="Sunrise Karate — Main Dojo" /></UFormField><UFormField label="Address or city"><UInput v-model="form.dojoAddress" placeholder="Indiranagar, Bengaluru" /></UFormField></div></section>
      <section v-else-if="step === 3"><p class="text-sm font-semibold text-primary">WHAT YOU TEACH</p><h1 class="mt-2 text-2xl font-semibold">Which martial art do you teach?</h1><p class="mt-2 text-sm text-slate-500">We will create a ready-to-use belt grading system for this program.</p><div class="mt-6 space-y-4"><UFormField label="Martial art"><USelect v-model="form.martialArt" :items="martialArtOptions" /></UFormField><UFormField label="Style or school"><USelect v-if="form.martialArt !== 'custom'" v-model="form.style" :items="styleOptions" /><UInput v-else v-model="form.style" placeholder="Enter your style" /></UFormField></div></section>
      <section v-else-if="step === 4"><p class="text-sm font-semibold text-primary">FEES</p><h1 class="mt-2 text-2xl font-semibold">Set your default student fee</h1><p class="mt-2 text-sm text-slate-500">New students at this dojo will receive this plan automatically.</p><div class="mt-6 grid gap-4 sm:grid-cols-2"><UFormField label="Fee plan name"><UInput v-model="form.feeName" /></UFormField><UFormField label="Amount (₹)"><UInput v-model.number="form.feeAmount" type="number" min="1" /></UFormField></div></section>
      <section v-else-if="step === 5"><p class="text-sm font-semibold text-primary">YOUR TEAM</p><h1 class="mt-2 text-2xl font-semibold">Add staff for this dojo <span class="text-slate-500">Optional</span></h1><p class="mt-2 text-sm text-slate-500">You create each staff member's temporary password and assign them to this location. They can change it after signing in.</p><div class="mt-6 space-y-4"><div v-for="(staff, index) in staffMembers" :key="index" class="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-2"><UInput v-model="staff.name" placeholder="Staff member name" /><UInput v-model="staff.email" type="email" placeholder="Email address" /><UInput v-model="staff.password" type="password" placeholder="Temporary password (8+ characters)" /><USelect v-model="staff.assignmentRole" :items="staffRoleOptions" /><UButton color="error" variant="ghost" class="sm:col-span-2 justify-self-start" @click="removeStaff(index)">Remove staff member</UButton></div><UButton type="button" variant="outline" icon="i-lucide-user-plus" @click="addStaff">Add staff member</UButton></div></section>
      <section v-else-if="step === 6"><p class="text-sm font-semibold text-primary">WORKSPACE OWNER</p><h1 class="mt-2 text-2xl font-semibold">Who will own and manage this workspace?</h1><p class="mt-2 text-sm text-slate-500">This is your personal account name. It will appear as the workspace owner, separate from the organization name.</p><div class="mt-6 space-y-4"><UFormField label="Workspace owner name"><UInput v-model="form.name" autofocus placeholder="Your full name" /></UFormField><UFormField label="Owner email address"><UInput v-model="form.email" type="email" /></UFormField><UFormField label="Choose a password"><UInput v-model="form.password" type="password" /></UFormField></div></section>
      <section v-else><p class="text-sm font-semibold text-primary">ALMOST READY</p><h1 class="mt-2 text-2xl font-semibold">Add a logo? <span class="text-slate-500">Optional</span></h1><UFormField class="mt-6" label="Organization logo"><UInput type="file" accept="image/*" @change="onFileChange" /></UFormField><div class="mt-6 rounded-2xl bg-slate-100 p-4 text-sm"><p class="font-semibold">Your workspace will include</p><ul class="mt-2 space-y-1 text-slate-600"><li>Your organization and first dojo</li><li>A {{ martialArtLabel }} program and belt ranks</li><li>A default fee plan ready for enrolment</li></ul></div></section>
      <div class="flex justify-between gap-3 pt-2"><UButton v-if="step > 1" type="button" color="neutral" variant="ghost" @click="step--">Back</UButton><span v-else /><UButton type="submit" :loading="loading">{{ step === totalSteps ? 'Create my ready-to-use workspace' : 'Continue' }}</UButton></div>
    </form>
    <p class="mt-6 text-center text-sm text-slate-500">Already have an account? <NuxtLink to="/auth/login" class="font-medium text-primary">Sign in</NuxtLink></p>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'auth' })
const toast = useToast(); const route = useRoute(); const step = ref(1); const totalSteps = 7; const loading = ref(false); const logoFile = ref<File | null>(null)
const form = reactive({ organizationName: '', workspaceSlug: '', dojoName: '', dojoAddress: '', feeName: 'Monthly tuition', feeAmount: null as number | null, name: '', email: '', password: '', martialArt: 'karate', style: 'goju_ryu' })
const trialPlan = computed(() => ['city-starter', 'city-pro', 'state-pro', 'national'].includes(String(route.query.trialPlan)) ? String(route.query.trialPlan) : null); const billingPeriod = computed(() => route.query.billingPeriod === 'monthly' ? 'monthly' : 'annual')
const martialArtOptions = [{ label: 'Karate', value: 'karate' }, { label: 'Taekwondo', value: 'taekwondo' }, { label: 'Judo', value: 'judo' }, { label: 'Brazilian Jiu-Jitsu', value: 'bjj' }, { label: 'Kung Fu / Wushu', value: 'kung_fu' }, { label: 'Muay Thai', value: 'muay_thai' }, { label: 'MMA', value: 'mma' }, { label: 'Something else', value: 'custom' }]
const styleOptions = computed(() => [{ label: 'Standard program', value: 'standard' }, { label: 'Goju-ryu', value: 'goju_ryu' }, { label: 'Shotokan', value: 'shotokan' }, { label: 'Custom school', value: 'custom' }]); const martialArtLabel = computed(() => martialArtOptions.find(item => item.value === form.martialArt)?.label || 'martial art')
const staffMembers = ref<Array<{ name: string, email: string, password: string, assignmentRole: 'instructor' | 'dojo_head' }>>([]); const staffRoleOptions = [{ label: 'Instructor', value: 'instructor' }, { label: 'Dojo manager', value: 'dojo_head' }]
watch(() => form.martialArt, () => { form.style = styleOptions.value[0].value })
function onFileChange(event: Event) { logoFile.value = (event.target as HTMLInputElement).files?.[0] || null }
function addStaff() { staffMembers.value.push({ name: '', email: '', password: '', assignmentRole: 'instructor' }) }; function removeStaff(index: number) { staffMembers.value.splice(index, 1) }
function validStep() { if (step.value === 1 && !form.organizationName.trim()) return 'Enter your organization name.'; if (step.value === 2 && !form.dojoName.trim()) return 'Enter your dojo name.'; if (step.value === 3 && !form.style.trim()) return 'Choose a style.'; if (step.value === 4 && (!form.feeName.trim() || !form.feeAmount || form.feeAmount < 1)) return 'Enter a fee plan name and amount.'; if (step.value === 5 && staffMembers.value.some(staff => !staff.name.trim() || !/^\S+@\S+\.\S+$/.test(staff.email) || staff.password.length < 8)) return 'Each staff member needs a name, valid email, and temporary password of at least 8 characters.'; if (step.value === 6) { if (!form.name.trim()) return 'Enter your name.'; if (!/^\S+@\S+\.\S+$/.test(form.email)) return 'Enter a valid email address.'; if (form.password.length < 8) return 'Choose a password with at least 8 characters.' }; return null }
async function next() { const message = validStep(); if (message) { toast.add({ color: 'warning', title: message }); return }; if (step.value < totalSteps) { step.value++; return }; loading.value = true; try { const fd = new FormData(); for (const [key, value] of Object.entries(form)) fd.append(key, String(value ?? '')); fd.append('staff', JSON.stringify(staffMembers.value)); if (trialPlan.value) { fd.append('trialPlan', trialPlan.value); fd.append('billingPeriod', billingPeriod.value) }; if (logoFile.value) fd.append('logo', logoFile.value); const response = await $fetch<any>('/api/onboarding', { method: 'POST', body: fd }); if (response.workspaceUrl) { window.location.assign(`${response.workspaceUrl}/auth/login?created=1&email=${encodeURIComponent(form.email)}`); return }; await navigateTo({ path: '/auth/login', query: { created: '1', email: form.email } }) } catch (error: any) { toast.add({ color: 'error', title: 'We could not create your workspace', description: error.data?.statusMessage || error.message }) } finally { loading.value = false } }
</script>
