<template>
  <article>
    <p class="text-sm font-semibold text-primary">LEGAL</p><h1 class="mt-2 text-4xl font-semibold tracking-tight">Privacy Policy</h1><p class="mt-4 text-sm text-slate-500 dark:text-slate-400">Effective date: July 13, 2026</p>
    <p class="mt-8 leading-7 text-slate-600 dark:text-slate-300">This Privacy Policy explains how {{ entityName }} handles personal information when you use OpenDojo. For information entered into an organization workspace, that organization generally decides why and how the information is used; OpenDojo processes it on the organization’s instructions to provide the Service.</p>
    <section v-for="section in sections" :key="section.title" class="mt-9"><h2 class="text-xl font-semibold">{{ section.title }}</h2><p v-for="paragraph in section.paragraphs" :key="paragraph" class="mt-3 leading-7 text-slate-600 dark:text-slate-300">{{ paragraph }}</p><ul v-if="section.items" class="mt-3 list-disc space-y-2 pl-6 leading-7 text-slate-600 dark:text-slate-300"><li v-for="item in section.items" :key="item">{{ item }}</li></ul></section>
    <section class="mt-9"><h2 class="text-xl font-semibold">Privacy contact</h2><p class="mt-3 leading-7 text-slate-600 dark:text-slate-300">For privacy requests or questions, contact <a :href="`mailto:${supportEmail}`" class="text-primary hover:underline">{{ supportEmail }}</a>. We may need to verify your identity or authority before responding.</p></section>
  </article>
</template>
<script setup lang="ts">
definePageMeta({ layout: 'legal' })
const { entityName, supportEmail } = useLegalContact()
useHead({ title: 'Privacy Policy | OpenDojo' })
const sections = [
  { title: '1. Information we collect', paragraphs: ['We collect information you provide when creating an account, configuring a workspace, contacting support, or using the Service. This may include account details, organization details, and operational records entered by authorized users.'], items: ['Account information, such as name, email address, role, and authentication details.', 'Organization and workspace information, such as organization name, logo, configuration, and hierarchy.', 'Operational information submitted by customers, including student, guardian, instructor, attendance, financial, document, and report data.', 'Technical and usage information, such as device, browser, log, and security information needed to operate and protect the Service.'] },
  { title: '2. How we use information', paragraphs: ['We use information to provide, secure, maintain, and improve the Service; authenticate users; process transactions; respond to support requests; communicate service-related updates; prevent fraud and misuse; and comply with legal obligations. We do not sell personal information or use customer data for targeted advertising.'] },
  { title: '3. Sharing and service providers', paragraphs: ['We share information only as necessary to deliver the Service, comply with law, protect rights and safety, or complete a business transaction such as a merger or acquisition. Service providers that help us host, secure, support, or process payments may process information under confidentiality and security obligations.'] },
  { title: '4. Retention and security', paragraphs: ['We retain information for as long as needed to provide the Service, meet legal obligations, resolve disputes, and enforce agreements. Workspace administrators can request deletion or export of their organization’s data, subject to legal retention requirements.', 'We use reasonable administrative, technical, and organizational safeguards. No system is completely secure; you are responsible for using strong credentials and limiting access to authorized users.'] },
  { title: '5. Your choices and rights', paragraphs: ['Depending on where you live, you may have rights to request access, correction, deletion, restriction, portability, or objection to certain processing. If your information was entered by an organization using OpenDojo, please contact that organization first; it controls the relevant workspace data.'] },
  { title: '6. Children’s information', paragraphs: ['OpenDojo is a business service for organizations and is not directed to children. Organizations that enter information about minors are responsible for obtaining parental or guardian consent and complying with laws that apply to them. We do not knowingly collect information directly from children for our own purposes.'] },
  { title: '7. International transfers and updates', paragraphs: ['Information may be processed in countries where we or our service providers operate. Where required, we use appropriate safeguards for cross-border transfers. We may revise this Policy to reflect changes to our practices or legal requirements; the effective date above indicates the latest version.'] },
]
</script>
