<template>
  <article>
    <p class="text-sm font-semibold text-primary">LEGAL</p><h1 class="mt-2 text-4xl font-semibold tracking-tight">Terms of Service</h1><p class="mt-4 text-sm text-slate-500 dark:text-slate-400">Effective date: July 13, 2026</p>
    <p class="mt-8 text-base leading-7 text-slate-600 dark:text-slate-300">These Terms govern your use of OpenDojo, a software-as-a-service platform for managing martial-arts organizations, dojos, people, classes, attendance, finances, documents, and reports. By creating an account, accessing, or using the Service, you agree to these Terms on behalf of yourself and, where applicable, the organization you represent.</p>
    <section v-for="section in sections" :key="section.title" class="mt-9"><h2 class="text-xl font-semibold">{{ section.title }}</h2><p v-for="paragraph in section.paragraphs" :key="paragraph" class="mt-3 leading-7 text-slate-600 dark:text-slate-300">{{ paragraph }}</p></section>
    <section class="mt-9"><h2 class="text-xl font-semibold">Contact</h2><p class="mt-3 leading-7 text-slate-600 dark:text-slate-300">Questions about these Terms may be sent to <a :href="`mailto:${supportEmail}`" class="text-primary hover:underline">{{ supportEmail }}</a>.</p></section>
  </article>
</template>
<script setup lang="ts">
definePageMeta({ layout: 'legal' })
const { entityName, supportEmail } = useLegalContact()
useHead({ title: 'Terms of Service | OpenDojo' })
const sections = [
  { title: '1. Accounts and authority', paragraphs: [`You must provide accurate account information, protect your credentials, and promptly notify ${entityName} of suspected unauthorized use. If you create or administer an organization workspace, you confirm that you are authorized to accept these Terms and manage information on that organization’s behalf.`] },
  { title: '2. Your data and responsibilities', paragraphs: ['You retain ownership of the content and personal data you submit to the Service. You are responsible for ensuring you have a lawful basis to collect, use, and share that data, including data relating to students, guardians, staff, and minors. You must obtain any permissions or consents required by applicable law and maintain accurate records.', 'You must not use the Service to store unlawful content, infringe others’ rights, send unsolicited communications, interfere with the Service, attempt unauthorized access, or upload malware.'] },
  { title: '3. Service access and acceptable use', paragraphs: ['We grant you a limited, non-exclusive, non-transferable right to use the Service during your active subscription or permitted trial, subject to these Terms. You may not reverse engineer, resell, lease, copy, or create derivative works from the Service except where applicable law does not allow that restriction.', 'We may suspend or restrict access when reasonably necessary to protect the Service, users, data, or compliance with law. Where practical, we will provide notice and an opportunity to address the issue.'] },
  { title: '4. Fees, renewals, and taxes', paragraphs: ['Paid plans, billing intervals, and any applicable limits are presented at checkout or in a separate order form. You authorize us or our payment provider to charge the applicable fees. Fees are due in advance, non-cancellable during a paid period except as required by law or stated in our Refund Policy, and exclude applicable taxes unless expressly stated otherwise.'] },
  { title: '5. Intellectual property', paragraphs: ['The Service, its software, design, documentation, and branding are owned by or licensed to OpenDojo and are protected by applicable intellectual-property laws. Feedback you provide may be used by us without restriction or compensation, provided we do not identify you as its source without permission.'] },
  { title: '6. Availability, disclaimers, and liability', paragraphs: ['We work to keep the Service secure and available, but do not guarantee uninterrupted, error-free, or loss-free operation. The Service is provided “as is” and “as available” to the extent permitted by law. You should maintain appropriate backups of records you need to retain.', 'To the fullest extent permitted by law, neither party is liable for indirect, incidental, special, consequential, or punitive damages. Our aggregate liability arising from the Service will not exceed the amount you paid us for the Service in the 12 months before the event giving rise to the claim. Nothing in these Terms limits liability that cannot legally be limited.'] },
  { title: '7. Termination and changes', paragraphs: ['You may stop using the Service at any time. We may terminate or suspend access for a material breach, unlawful use, non-payment, or where required to protect the Service or others. On termination, your right to use the Service ends; you should export your data before your access ends.', 'We may update these Terms from time to time. Material changes will be communicated through the Service or by email where appropriate. Continued use after the effective date of updated Terms constitutes acceptance.'] },
  { title: '8. Governing law', paragraphs: ['These Terms are governed by the laws applicable to the entity operating OpenDojo, without regard to conflict-of-law rules. Any mandatory consumer rights that apply to you remain unaffected.'] },
]
</script>
