<template>
  <div class="mx-auto max-w-5xl">
    <section class="mb-6"><p class="text-sm font-semibold text-primary">OPERATIONS</p><h2 class="mt-1 text-2xl font-semibold">Tournament management</h2></section>
    <UCard><template #header><h3 class="font-semibold">{{ editingTournamentId ? 'Edit tournament' : 'Create tournament' }}</h3></template><form class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" @submit.prevent="saveTournament"><UFormField label="Name" required><UInput v-model="form.name" required /></UFormField><UFormField label="Level" required><UInput v-model="form.level" required /></UFormField><UFormField label="Venue"><UInput v-model="form.venue" /></UFormField><UFormField label="Start date" required><UInput v-model="form.startDate" type="date" required /></UFormField><UFormField label="End date"><UInput v-model="form.endDate" type="date" /></UFormField><UFormField label="Age cut-off date" help="Student ages are calculated on this date." required><UInput v-model="form.ageCutoffDate" type="date" required /></UFormField><div class="self-end flex gap-2"><UButton type="submit" :loading="saving">{{ editingTournamentId ? 'Save tournament' : 'Create tournament' }}</UButton><UButton v-if="editingTournamentId" type="button" color="neutral" variant="ghost" @click="resetTournamentForm">Cancel</UButton></div></form></UCard>
    <UCard v-for="item in tournaments" :key="item.id" class="mt-6"><template #header><div class="flex justify-between gap-4"><div><h3 class="font-semibold">{{ item.name }}</h3><p class="text-sm text-slate-500">{{ item.level }} · {{ formatDate(item.startDate) }} · {{ item.venue || 'Venue not set' }}</p><p class="mt-1 text-xs text-slate-400">Age cut-off: {{ formatDate(item.ageCutoffDate || item.startDate) }}</p></div><div class="flex shrink-0 items-start gap-2"><UButton size="sm" color="neutral" variant="outline" @click="editTournament(item)">Edit</UButton><UButton size="sm" color="error" variant="outline" @click="deleteTournament(item)">Delete</UButton><UButton size="sm" @click="selectTournament(item.id)">{{ selectedId === item.id ? 'Close roster' : 'Manage participants' }}</UButton></div></div></template>
      <div v-if="selectedId === item.id"><form class="grid gap-4 rounded-xl border border-slate-200 p-4 sm:grid-cols-2 lg:grid-cols-3 dark:border-slate-800" @submit.prevent="saveEntry"><UFormField label="Student" required><USelect v-model="entry.studentId" :items="studentOptions" searchable required :disabled="!!editingId" /></UFormField><UFormField label="Student age"><UInput :model-value="studentAge" readonly placeholder="Select a student" /></UFormField><UFormField label="Event" required><USelect v-model="entry.eventType" :items="eventOptions" required /></UFormField><UFormField label="Belt division" required><USelect v-model="entry.beltDivision" :items="beltOptions" required /></UFormField><UFormField label="Competition category"><USelect v-model="entry.ageCategory" :items="ageCategoryOptions" placeholder="Select category" /></UFormField><UFormField label="Weight category"><UInput v-model="entry.weightCategory" /></UFormField><div class="self-end flex gap-2"><UButton type="submit" :loading="savingEntry">{{ editingId ? 'Save entry' : 'Add participant' }}</UButton><UButton v-if="editingId" type="button" color="neutral" variant="ghost" @click="resetEntry">Cancel</UButton></div></form>
        <div class="mt-6 grid gap-5 lg:grid-cols-2"><section v-for="group in [{ title: 'Colour belts', items: colourEntries }, { title: 'Brown / Black belts', items: brownBlackEntries }]" :key="group.title" class="rounded-xl border border-slate-200 dark:border-slate-800"><h4 class="border-b border-slate-200 px-4 py-3 font-semibold dark:border-slate-800">{{ group.title }} ({{ group.items.length }})</h4><div v-if="group.items.length" class="divide-y divide-slate-100 dark:divide-slate-800"><div v-for="item in group.items" :key="item.id" class="flex items-center justify-between gap-3 p-4"><div><p class="font-medium">{{ item.student?.firstName }} {{ item.student?.lastName }}</p><p class="text-sm capitalize text-slate-500">{{ item.eventType }}<span v-if="item.ageCategory"> · {{ item.ageCategory }}</span><span v-if="item.weightCategory"> · {{ item.weightCategory }}</span></p></div><div class="flex gap-1"><UButton size="xs" variant="ghost" @click="editEntry(item)">Edit</UButton><UButton size="xs" color="error" variant="ghost" @click="removeEntry(item)">Delete</UButton></div></div></div><p v-else class="p-5 text-sm text-slate-500">No participants yet.</p></section></div></div>
    </UCard>
  </div>
</template>
<script setup lang="ts">
definePageMeta({ middleware: 'auth' }); const toast = useToast(); const saving = ref(false); const savingEntry = ref(false); const selectedId = ref<number | null>(null); const editingId = ref<number | null>(null); const editingTournamentId = ref<number | null>(null); const entries = ref<any[]>([])
const form = reactive({ name: '', level: '', venue: '', startDate: '', endDate: '', ageCutoffDate: '' }); const entry = reactive({ studentId: null as number | null, eventType: 'kata', beltDivision: 'colour', ageCategory: '', weightCategory: '' })
const { data: tournaments, refresh } = await useFetch<any[]>('/api/tournaments'); const { data: students } = await useFetch<any[]>('/api/students'); const eventOptions = [{ label: 'Kata', value: 'kata' }, { label: 'Kumite', value: 'kumite' }]; const beltOptions = [{ label: 'Colour belts', value: 'colour' }, { label: 'Brown / Black belts', value: 'brown_black' }]; const ageCategoryOptions = [{ label: 'U-12 (Under 12)', value: 'U-12' }, { label: 'U-14 (Under 14)', value: 'U-14' }, { label: 'Sub Junior (Under 14)', value: 'Sub Junior' }, { label: 'Cadet (14–15)', value: 'Cadet' }, { label: 'Junior (16–17)', value: 'Junior' }, { label: 'U-21 (18–20)', value: 'U-21' }, { label: 'Senior (Above 21)', value: 'Senior' }]; const studentOptions = computed(() => (students.value || []).filter(s => s.status === 'active').map(s => ({ label: `${s.firstName} ${s.lastName}`, value: s.id }))); const selectedStudent = computed(() => (students.value || []).find(student => student.id === entry.studentId)); const selectedTournament = computed(() => (tournaments.value || []).find(tournament => tournament.id === selectedId.value)); const studentAge = computed(() => ageAt(selectedStudent.value?.dateOfBirth, selectedTournament.value?.ageCutoffDate || selectedTournament.value?.startDate)); const colourEntries = computed(() => entries.value.filter(e => e.beltDivision !== 'brown_black')); const brownBlackEntries = computed(() => entries.value.filter(e => e.beltDivision === 'brown_black'))
function formatDate(value: string) { return new Date(value).toLocaleDateString() }; function ageAt(dateOfBirth?: string | null, onDate?: string | null) { if (!dateOfBirth) return ''; const birth = new Date(dateOfBirth); const date = onDate ? new Date(onDate) : new Date(); let age = date.getFullYear() - birth.getFullYear(); if (date.getMonth() < birth.getMonth() || (date.getMonth() === birth.getMonth() && date.getDate() < birth.getDate())) age--; return `${age} years`; }; function resetEntry() { Object.assign(entry, { studentId: null, eventType: 'kata', beltDivision: 'colour', ageCategory: '', weightCategory: '' }); editingId.value = null }
function resetTournamentForm() { Object.assign(form, { name: '', level: '', venue: '', startDate: '', endDate: '', ageCutoffDate: '' }); editingTournamentId.value = null }
function dateInputValue(value?: string | null) { return value ? new Date(value).toISOString().slice(0, 10) : '' }
function editTournament(tournament: any) { editingTournamentId.value = tournament.id; Object.assign(form, { name: tournament.name, level: tournament.level, venue: tournament.venue || '', startDate: dateInputValue(tournament.startDate), endDate: dateInputValue(tournament.endDate), ageCutoffDate: dateInputValue(tournament.ageCutoffDate || tournament.startDate) }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
async function saveTournament() { saving.value = true; try { const body = { ...form, venue: form.venue || undefined, endDate: form.endDate || undefined }; const isEditing = !!editingTournamentId.value; if (isEditing) await $fetch(`/api/tournaments/${editingTournamentId.value}`, { method: 'PATCH', body }); else await $fetch('/api/tournaments', { method: 'POST', body }); await refresh(); resetTournamentForm(); toast.add({ color: 'success', title: isEditing ? 'Tournament updated' : 'Tournament created' }) } catch (error: any) { toast.add({ color: 'error', title: 'Could not save tournament', description: error.data?.statusMessage || error.message }) } finally { saving.value = false } }
async function deleteTournament(tournament: any) { if (!confirm(`Delete ${tournament.name}? Student achievement history will be preserved.`)) return; try { await $fetch(`/api/tournaments/${tournament.id}`, { method: 'DELETE' }); if (selectedId.value === tournament.id) { selectedId.value = null; entries.value = [] }; if (editingTournamentId.value === tournament.id) resetTournamentForm(); await refresh(); toast.add({ color: 'success', title: 'Tournament deleted' }) } catch (error: any) { toast.add({ color: 'error', title: 'Could not delete tournament', description: error.data?.statusMessage || error.message }) } }
async function selectTournament(id: number) { if (selectedId.value === id) { selectedId.value = null; return }; selectedId.value = id; entries.value = await $fetch(`/api/tournaments/${id}/entries`); resetEntry() }
async function saveEntry() { if (!selectedId.value || !entry.studentId) return; savingEntry.value = true; try { const url = editingId.value ? `/api/tournaments/${selectedId.value}/entries/${editingId.value}` : `/api/tournaments/${selectedId.value}/entries`; await $fetch(url, { method: editingId.value ? 'PATCH' : 'POST', body: entry }); entries.value = await $fetch(`/api/tournaments/${selectedId.value}/entries`); resetEntry(); toast.add({ color: 'success', title: 'Participant saved' }) } finally { savingEntry.value = false } }
function editEntry(value: any) { editingId.value = value.id; Object.assign(entry, { studentId: value.studentId, eventType: value.eventType, beltDivision: value.beltDivision || 'colour', ageCategory: value.ageCategory || '', weightCategory: value.weightCategory || '' }) }
async function removeEntry(value: any) { if (!selectedId.value || !confirm(`Remove ${value.student?.firstName} from this tournament?`)) return; await $fetch(`/api/tournaments/${selectedId.value}/entries/${value.id}`, { method: 'DELETE' }); entries.value = await $fetch(`/api/tournaments/${selectedId.value}/entries`) }
const Roster = defineComponent({ props: { title: String, items: Array }, emits: ['edit', 'remove'], template: '<section class="rounded-xl border border-slate-200 dark:border-slate-800"><div class="border-b border-slate-200 px-4 py-3 font-semibold dark:border-slate-800">{{ title }}</div><div v-if="items?.length" class="divide-y divide-slate-100 dark:divide-slate-800"><div v-for="item in items" :key="item.id" class="flex items-center justify-between gap-3 p-4"><div><p class="font-medium">{{ item.student?.firstName }} {{ item.student?.lastName }}</p><p class="text-sm capitalize text-slate-500">{{ item.eventType }}<span v-if="item.ageCategory"> · {{ item.ageCategory }}</span><span v-if="item.weightCategory"> · {{ item.weightCategory }}</span></p></div><div class="flex gap-1"><UButton size="xs" variant="ghost" @click="$emit(\'edit\', item)">Edit</UButton><UButton size="xs" color="error" variant="ghost" @click="$emit(\'remove\', item)">Delete</UButton></div></div></div><p v-else class="p-5 text-sm text-slate-500">No participants yet.</p></section>' })
</script>
<style scoped>
form :deep(button[role="combobox"]) { min-width: 12rem; width: 100%; }
</style>
