CREATE TABLE `governing_bodies` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `organization_id` integer NOT NULL,
  `name` text NOT NULL,
  `level` text DEFAULT 'other' NOT NULL,
  `country` text,
  `website` text,
  `contact_name` text,
  `contact_email` text,
  `contact_phone` text,
  `notes` text,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL,
  FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade
);
CREATE TABLE `affiliations` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `organization_id` integer NOT NULL,
  `governing_body_id` integer NOT NULL,
  `scope_type` text NOT NULL,
  `scope_id` integer,
  `relationship_type` text NOT NULL,
  `membership_number` text,
  `status` text DEFAULT 'pending' NOT NULL,
  `started_at` integer,
  `expires_at` integer,
  `renewal_due_at` integer,
  `fee_amount` integer,
  `fee_frequency` text,
  `document_url` text,
  `notes` text,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL,
  FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
  FOREIGN KEY (`governing_body_id`) REFERENCES `governing_bodies`(`id`) ON UPDATE no action ON DELETE cascade
);
CREATE TABLE `expenses` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `organization_id` integer NOT NULL,
  `affiliation_id` integer,
  `scope_type` text NOT NULL,
  `scope_id` integer,
  `category` text NOT NULL,
  `payee` text,
  `description` text NOT NULL,
  `invoice_number` text,
  `amount` integer NOT NULL,
  `tax_amount` integer DEFAULT 0 NOT NULL,
  `incurred_at` integer NOT NULL,
  `due_at` integer,
  `paid_at` integer,
  `status` text DEFAULT 'due' NOT NULL,
  `receipt_url` text,
  `notes` text,
  `created_by` integer,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL,
  FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
  FOREIGN KEY (`affiliation_id`) REFERENCES `affiliations`(`id`) ON UPDATE no action ON DELETE set null,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
