CREATE TABLE `student_achievements` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `organization_id` integer NOT NULL,
  `student_id` integer NOT NULL,
  `tournament_name` text NOT NULL,
  `tournament_level` text NOT NULL,
  `venue` text,
  `start_date` integer NOT NULL,
  `end_date` integer,
  `event_type` text,
  `age_category` text,
  `weight_category` text,
  `result` text,
  `medals_won` integer DEFAULT 0 NOT NULL,
  `certificate_url` text,
  `notes` text,
  `created_by` integer,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL,
  FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
  FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON UPDATE no action ON DELETE cascade,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
