<template>
  <div class="mx-auto max-w-5xl"><div class="mb-6"><UButton to="/tournaments" color="neutral" variant="ghost" icon="i-lucide-arrow-left">Tournaments</UButton><h2 class="mt-3 text-2xl font-semibold">{{ tournament?.name || 'Tournament' }}</h2><p class="mt-1 text-sm text-slate-500">Register participants by event. Add the same student twice when they compete in both Kata and Kumite.</p></div><UCard><template #header><h3 class="font-semibold">Add participant</h3></template><form class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" @submit.prevent="addEntry"><UFormField label="Student" required><USelect v-model="form.studentId" :items="studentOptions" searchable placeholder="Select student" required /></UFormField><UFormField label="Student age"><UInput :model-value="studentAge" readonly placeholder="Select a student" /></UFormField><UFormField label="Event" required><USelect v-model="form.eventType" :items="eventOptions" required /></UFormField><UFormField label="Competition category"><USelect v-model="form.ageCategory" :items="ageCategoryOptions" placeholder="Select category" /></UFormField><UFormField label="Weight category"><UInput v-model="form.weightCategory" placeholder="For Kumite" /></UFormField><div class="sm:col-span-2 lg:col-span-4"><UButton type="submit" :loading="saving">Register participant</UButton></div></form></UCard><UCard class="mt-6"><template #header><h3 class="font-semibold">Registered entries</h3></template><div v-if="entries?.length" class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="border-b border-slate-100 text-left text-xs uppercase text-slate-400 dark:border-slate-800"><tr><th class="px-3 py-3">Student</th><th class="px-3 py-3">Event</th><th class="px-3 py-3">Competition category</th><th class="px-3 py-3">Weight category</th><th class="px-3 py-3">Result</th></tr></thead><tbody><tr v-for="entry in entries" :key="entry.id" class="border-b border-slate-100 last:border-0 dark:border-slate-800"><td class="px-3 py-4 font-medium">{{ entry.student?.firstName }} {{ entry.student?.lastName }}</td><td class="px-3 py-4 capitalize">{{ entry.eventType }}</td><td class="px-3 py-4">{{ entry.ageCategory || '—' }}</td><td class="px-3 py-4">{{ entry.weightCategory || '—' }}</td><td class="px-3 py-4">{{ entry.result || 'Awaiting result' }}</td></tr></tbody></table></div><p v-else class="py-8 text-center text-sm text-slate-500">No participants registered yet.</p></UCard></div>
</template>
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const route = useRoute(); const id = Number(route.params.id); const toast = useToast(); const saving = ref(false)
const { data: tournaments } = await useFetch<any[]>('/api/tournaments'); const tournament = computed(() => (tournaments.value || []).find(item => item.id === id))
const { data: students } = await useFetch<any[]>('/api/students'); const { data: entries, refresh } = await useFetch<any[]>(`/api/tournaments/${id}/entries`)
const form = reactive({ studentId: null as number | null, eventType: 'kata', ageCategory: '', weightCategory: '' }); const eventOptions = [{ label: 'Kata', value: 'kata' }, { label: 'Kumite', value: 'kumite' }]; const ageCategoryOptions = [{ label: 'U-12 (Under 12)', value: 'U-12' }, { label: 'U-14 (Under 14)', value: 'U-14' }, { label: 'Sub Junior (Under 14)', value: 'Sub Junior' }, { label: 'Cadet (14–15)', value: 'Cadet' }, { label: 'Junior (16–17)', value: 'Junior' }, { label: 'U-21 (18–20)', value: 'U-21' }, { label: 'Senior (Above 21)', value: 'Senior' }]; const studentOptions = computed(() => (students.value || []).filter(student => student.status === 'active').map(student => ({ label: `${student.firstName} ${student.lastName}${student.dojo?.name ? ` — ${student.dojo.name}` : ''}`, value: student.id }))); const studentAge = computed(() => { const student = (students.value || []).find(item => item.id === form.studentId); if (!student?.dateOfBirth) return ''; const birth = new Date(student.dateOfBirth); const date = tournament.value?.ageCutoffDate ? new Date(tournament.value.ageCutoffDate) : tournament.value?.startDate ? new Date(tournament.value.startDate) : new Date(); let age = date.getFullYear() - birth.getFullYear(); if (date.getMonth() < birth.getMonth() || (date.getMonth() === birth.getMonth() && date.getDate() < birth.getDate())) age--; return `${age} years` })
async function addEntry() { if (!form.studentId) return; saving.value = true; try { await $fetch(`/api/tournaments/${id}/entries`, { method: 'POST', body: { ...form, ageCategory: form.ageCategory || undefined, weightCategory: form.weightCategory || undefined } }); Object.assign(form, { studentId: null, eventType: 'kata', ageCategory: '', weightCategory: '' }); await refresh(); toast.add({ color: 'success', title: 'Participant registered' }) } catch (error: any) { toast.add({ color: 'error', title: 'Could not register participant', description: error.data?.statusMessage || error.message }) } finally { saving.value = false } }
</script>
